docs: add docs for schemas as database for oracle
bytebase/bytebase.com pull request #124
Opened 2023-07-18 03:28 UTC by rebelice

2023-07-18 03:51 UTC, milasuperstar requested changes

2023-07-18 03:51 UTC, milasuperstar commented on content/docs/how-to/oracle/how-to-sync-schemas-as-database-for-oracle.md
> +
```suggestion
```

2023-07-20 05:19 UTC, tianzhou requested changes
This can be put at https://www.bytebase.com/docs/get-started/instance/

create an oracle section

2023-07-20 06:35 UTC, rebelice commented
Updated. PTAL @milasuperstar @tianzhou

2023-07-20 07:08 UTC, tianzhou approved these changes
LGTM

2023-07-20 07:08 UTC, merged