feat: add subscribtion section to footer
bytebase/bytebase.com pull request #128
Opened 2022-04-28 08:58 UTC by boojack

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/24653555/165716467-eb87053a-d5d0-412f-b05a-7fb93a5bc782.png">

2022-04-28 14:40 UTC, tianzhou requested changes
Per offline discussion, let's create a full-width action area in the footer

2022-04-28 14:41 UTC, tianzhou requested changes
Per offline discussion, let's create a full-width action area in the footer

2022-04-29 02:21 UTC, boojack commented
PTAL

2022-04-29 02:49 UTC, tianzhou approved these changes
LGTM

2022-04-29 02:50 UTC, merged