feat(sql-editor): add the sql-editor section
bytebase/bytebase.com pull request #20
Opened 2022-02-16 10:46 UTC by xiaoluoboding

2022-02-16 11:21 UTC, tianzhou requested changes
Also to improve screenshot quality, let's construct real world example, like the product example on the top.

Currently, the screenshot shows some test name data, which is a bit lame.

2022-02-16 11:21 UTC, tianzhou commented on pages/index.vue
> +                  <svg class="w-6 h-6 text-white" width="32" height="32" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><g fill="none"><path d="M5 12h14M5 12a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h14
Let's remove the icon as it's getting really hard to find meaningful icons....

2022-02-16 12:44 UTC, xiaoluoboding commented on pages/index.vue
> +                  Easily explore the database connection with Project-based access control, and you can select table to see the schema information.
OK. remove alter schema for now.

2022-02-18 03:36 UTC, tianzhou commented on pages/index.vue
> +          Easy-to-use query interface to SELECT database records.
```suggestion
          Inspect records, explore schema, sharing SQL scripts, and more.
```

2022-02-18 03:38 UTC, tianzhou commented on pages/index.vue
> +                  Easily explore the database connection with Project-based access control, and you can select a table to see its schema.
```suggestion
                  Explore the database record and schema guarded by the project-level access control.
```

2022-02-18 03:39 UTC, tianzhou commented on pages/index.vue
> +                  Write queries effectively
```suggestion
                  Smooth query editing experience
```

2022-02-18 03:41 UTC, tianzhou commented on pages/index.vue
> +                  Enjoy the powerful built-in text editor based on Monaco Editor, with autocomplete suggestions, format SQL, shortcuts, and more.
```suggestion
                  Autocomplete suggestions, SQL format, shortcuts, and more.
```

2022-02-18 03:44 UTC, tianzhou commented on pages/index.vue
> +                  Never miss your sheets
```suggestion
                  Never miss your work
```

2022-02-18 03:44 UTC, tianzhou commented on pages/index.vue
> +                  The sheets allows you to easily find them and reuse it later by saving them, and share them with your teammates.
```suggestion
                  Save your favorite sheets and auto-record the execution history.
```

2022-02-18 03:48 UTC, tianzhou commented on pages/index.vue
> +                  Share the sheet as a link on the SQL statement with your teammates, with sharing options easily manage the sheet permissions.
```suggestion
                  Share the sheet link with your teammates, with configurable access levels.
```

2022-02-18 03:48 UTC, tianzhou commented on pages/index.vue
> +              <img
Ideally, overlay a history tab screenshot here as well.

2022-02-18 06:05 UTC, xiaoluoboding commented
PTAL

2022-02-18 06:08 UTC, tianzhou approved these changes
LGTM

2022-02-18 06:09 UTC, merged