docs: DBA, Database and Developer - The Decameron
bytebase/bytebase.com pull request #224
Opened 2022-06-06 07:19 UTC by LucyLu8L

I‘ve added the md document and a static picture, please review.

2022-06-06 07:56 UTC, boojack requested changes

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +# DBA, Database and Developer - The Decameron
Don't need to add this line. We will render the header title according to `title: xxxx`.

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +A few days ago, we posted a question on HN:[ Ask HN: Is DBA still a good job?](https://news.ycombinator.com/item?id=31309729) The question quickly drew the attention of the HN community and got 236 t
```suggestion
A few days ago, we posted a question on HN: [Ask HN: Is DBA still a good job?](https://news.ycombinator.com/item?id=31309729) The question quickly drew the attention of the HN community and got 236 thought-provoking comments. We share and feel the challenges, the frustration, the fatigue and the expectation. 
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +As the debut of this series, we compiled 10 stories about DBAs based on the replies and comments from the[ HN thread](https://news.ycombinator.com/item?id=31309729): we adopted the Decameron style, m
```suggestion
As the debut of this series, we compiled 10 stories about DBAs based on the replies and comments from the [HN thread](https://news.ycombinator.com/item?id=31309729): we adopted the Decameron style, made up the story background, and borrowed the true stories shared by the commenters and turned them over to the storytellers (all credits go to the rightful owners). Some of these storytellers had experience as full-time DBAs; the others may be developers who have worked with DBAs before. You can regard this article as the appetizer of a full course meal. The crew welcomes all kinds of feedback and, last but not least: Bon Appetite! 
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 1 From[ donatj](https://news.ycombinator.com/user?id=donatj): Honestly Wish We had a DBA**
```suggestion
## Day 1 From [donatj](https://news.ycombinator.com/user?id=donatj): Honestly Wish We had a DBA
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 2  From[ steve_adams_86](https://news.ycombinator.com/user?id=steve_adams_86): Both Brilliant, both jerks**
```suggestion
## Day 2  From [steve_adams_86](https://news.ycombinator.com/user?id=steve_adams_86): Both Brilliant, both jerks
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 3 From[ jamal-kumar](https://news.ycombinator.com/user?id=jamal-kumar): Gone DBA**
```suggestion
## Day 3 From [jamal-kumar](https://news.ycombinator.com/user?id=jamal-kumar): Gone DBA
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 4 From[ Simon_O_Rourke](https://news.ycombinator.com/user?id=Simon_O_Rourke): He was Supposed to Know Everything**
```suggestion
## Day 4 From [Simon_O_Rourke](https://news.ycombinator.com/user?id=Simon_O_Rourke): He was Supposed to Know Everything
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 5 From[ skc](https://news.ycombinator.com/user?id=skc): “UR RUINING MY F****ING DATABASE”**
```suggestion
## Day 5 From [skc](https://news.ycombinator.com/user?id=skc): “UR RUINING MY F****ING DATABASE”
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 6 From[ forinti](https://news.ycombinator.com/user?id=forinti): Try to be the person I needed help from before**
```suggestion
## Day 6 From [forinti](https://news.ycombinator.com/user?id=forinti): Try to be the person I needed help from before
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 7 From[ compton93](https://news.ycombinator.com/user?id=compton93): For that company my role was priceless**
```suggestion
## Day 7 From [compton93](https://news.ycombinator.com/user?id=compton93): For that company my role was priceless
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 8 From[ Twisell](https://news.ycombinator.com/user?id=Twisell): Exhausting yet rewarding**
```suggestion
## Day 8 From [Twisell](https://news.ycombinator.com/user?id=Twisell): Exhausting yet rewarding
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 9 From[ jhugo](https://news.ycombinator.com/user?id=jhugo): Conflict comes from lack of understanding**
```suggestion
## Day 9 From [jhugo](https://news.ycombinator.com/user?id=jhugo): Conflict comes from lack of understanding
```

2022-06-06 07:56 UTC, boojack commented on content/blog/ddd-decameron.md
> +## Day 10 From[ niklasrde](https://news.ycombinator.com/user?id=niklasrde) &[ datalopers](https://news.ycombinator.com/user?id=datalopers): The lost art -- data modeling and SQL**
```suggestion
## Day 10 From [niklasrde](https://news.ycombinator.com/user?id=niklasrde) &[ datalopers](https://news.ycombinator.com/user?id=datalopers): The lost art -- data modeling and SQL
```

2022-06-06 13:47 UTC, tianzhou requested changes

2022-06-06 13:47 UTC, tianzhou commented on content/blog/ddd-decameron.md
> +---
ddd-decameron.md is not SEO friendly.

Let's use "dba-database-developer-decameron"

2022-06-06 14:04 UTC, LucyLu8L commented on content/blog/ddd-decameron.md
> +title: "DBA, Database and Developer - The Decameron"
to emphasize our special attention to DBA; plus database is more of a media in these stories, they are more focused on the relationship and interaction between DBAs and Developers

2022-06-07 02:23 UTC, boojack requested changes
You can preview the article by https://bytebase-com-git-docs-ddd-decameron-bytebase.vercel.app/blog/dba-database-developer-decameron

2022-06-07 02:23 UTC, boojack commented on content/blog/dba-database-developer-decameron.md
> +![RoaringDBA](https://bytebase.com/static/blog-changelog-assets/2022/06/roaringdba.jpeg)
Don't need to add the prefix in `.md` file.

2022-06-07 06:03 UTC, LucyLu8L commented
all review suggestions committed, please review again

2022-06-08 02:15 UTC, boojack approved these changes
LGTM

2022-06-08 02:15 UTC, boojack commented on content/blog/dba-database-developer-decameron.md
> +A few days ago, we posted a question on HN: [Ask HN: Is DBA still a good job?](https://news.ycombinator.com/item?id=31309729) The question quickly drew the attention of the HN community and got 236 t
```suggestion

A few days ago, we posted a question on HN: [Ask HN: Is DBA still a good job?](https://news.ycombinator.com/item?id=31309729) The question quickly drew the attention of the HN community and got 236 thought-provoking comments. We share and feel the challenges, the frustration, the fatigue and the expectation. 
```

2022-06-08 07:53 UTC, tianzhou approved these changes
LGTM. Ship it

2022-06-08 07:53 UTC, merged