docs(schema-review): add features/schema-review docs
bytebase/bytebase.com pull request #234
Opened 2022-06-08 10:39 UTC by rebelice

TODO

- [ ] add screenshot for each rule
- [ ] add docs in use bytebase

2022-06-09 11:08 UTC, tianzhou requested changes
Good try.

2022-06-09 11:08 UTC, tianzhou commented on content/docs/en/features/schema-review/table-require-pk.md
> +In MySQL, [the InnoDB storage engine always creates a primary key](https://dev.mysql.com/doc/refman/8.0/en/innodb-index-types.html) if you didn't specify it explicitly or didn't create an unique key,
### 
```suggestion
In MySQL, [the InnoDB storage engine always creates a primary key](https://dev.mysql.com/doc/refman/8.0/en/innodb-index-types.html) if you didn't specify it explicitly or didn't create a unique key, thus making an extra column you don't have access to.
```

2022-06-09 11:08 UTC, tianzhou commented on content/docs/en/features/schema-review/table-require-pk.md
> +Bytebase considers this rule to be violated if the SQL try to create a no primary key table or drop the primary key. If SQL drops all tables in primary key, Bytebase also considers that this SQL drop
> If SQL drops all tables in primary key, Bytebase also considers that this SQL drops the primary key.

Not quite get this part

2022-06-09 11:08 UTC, tianzhou commented on content/docs/en/use-bytebase/schema-review/create-schema-review-policy.md
> +The `Schema Review Policy` is a 3-step creation.
```suggestion
Creating the `Schema Review Policy` is a 3-step process.
```

2022-06-09 11:08 UTC, tianzhou commented on content/docs/en/use-bytebase/schema-review/create-schema-review-policy.md
> +Note that only **ONE** policy can be created per `Environment`.
```suggestion
Note that only **ONE** policy can be attached per `Environment`.
```

2022-06-09 11:08 UTC, tianzhou commented on content/docs/en/use-bytebase/schema-review/create-schema-review-policy.md
> +There are currently three types of rules that need to be configuration.
```suggestion
There are currently three types of rules that need to be configured.
```

2022-06-09 11:08 UTC, tianzhou commented on content/docs/en/use-bytebase/schema-review/overview.md
> +You can know what is schema review [here](/docs/features/schema-review/overview).
THe link can be inlined with the configure `schema review` above

2022-06-09 11:08 UTC, tianzhou commented on content/docs/en/use-bytebase/schema-review/overview.md
> +Schema Review requires **Team Plan**.
```suggestion
Schema Review requires at least **Team Plan**.
```

2022-06-09 11:08 UTC, tianzhou commented on content/docs/en/use-bytebase/schema-review/overview.md
> +Bytebase defines `Schema Review Policy` for each `Environment`. The `Schema Review Policy` is essentially a set of SQL lint rules, and we call SQL lint rule the `Schema Review Rule`. After this, Byte
```suggestion
Bytebase defines `Schema Review Policy` for each `Environment`. The `Schema Review Policy` is essentially a set of SQL lint rules, and we call SQL lint rule the `Schema Review Rule`. Once configured, Bytebase will check SQL according to the corresponding `Schema Review Policy`.
```

2022-06-10 00:53 UTC, ecmadao approved these changes
LGTM. Do we need to convert these `png` to `webp`?

2022-06-10 03:20 UTC, d-bytebase commented on content/docs/en/features/schema-review/column-no-null.md
> +---
Any reason that we need a different page for each rule? Might be easier for customers to do Ctrl+F on a single page.

2022-06-10 03:28 UTC, rebelice commented on content/docs/en/features/schema-review/column-no-null.md
> +---
I'm worried that putting them all on a single page would be too long.

Customers can search rules on `features/schema-review/overview` or `www.bytebase.com/database-review-guide`.
On the other hand, Ctrl+F still works because we have a sidebar.

![image](https://user-images.githubusercontent.com/20775801/172984550-ec1f0cb7-e290-4758-a5fa-2617e9501ee7.png)

2022-06-10 03:39 UTC, rebelice commented on content/docs/en/features/schema-review/column-no-null.md
> +## Support instance engine
Sadly, `include-block` cannot recognize markdown formatting correctly, which means the include-block is just a line of text.

![image](https://user-images.githubusercontent.com/20775801/172985585-596aa535-0bcc-4698-9644-29431f00d9f8.png)

2022-06-10 04:14 UTC, rebelice commented
I have addressed all comments. PTAL @tianzhou @ecmadao @d-bytebase

2022-06-10 08:57 UTC, ecmadao submitted a review, later dismissed
LGTM

2022-06-10 10:28 UTC, tianzhou requested changes
More nits

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-table.md
> +`Table Naming Convention` uses [regular expression](https://en.wikipedia.org/wiki/Regular_expression) as format.
```suggestion
`Table Naming Convention` uses [regular expression](https://en.wikipedia.org/wiki/Regular_expression) as the format.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-table.md
> +### Some useful format
```suggestion
### Some typical format
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-table.md
> +Bytebase checks that all table names in DDL conform to naming conventions.
```suggestion
Bytebase checks that all table names in DDL conform to the naming conventions.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-column.md
> +`Column Naming Convention` uses [regular expression](https://en.wikipedia.org/wiki/Regular_expression) as format.
```suggestion
`Column Naming Convention` uses [regular expression](https://en.wikipedia.org/wiki/Regular_expression) format.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-column.md
> +### Some useful format
```suggestion
### Some typical format
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-column.md
> +Bytebase checks that all column names in DDL conform to naming conventions.
```suggestion
Bytebase checks that all column names in DDL conform to the naming conventions.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-idx.md
> +`Index Naming Convention` uses `template` as format. Specifically, the `template` is an extended [regular expression](https://en.wikipedia.org/wiki/Regular_expression). The rest follows the rules of
```suggestion
`Index Naming Convention` uses `template` format. Specifically, the `template` is an extended [regular expression](https://en.wikipedia.org/wiki/Regular_expression). The rest follows the regular expression rules except the part with curly braces.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-idx.md
> +For example, `^idx_{{table}}_{{column_list}}$` is a `template` where `{{table}}` is the name of table and `{{column_list}}` is the list of the column name. So for index on `user(id, name)`, the legal
```suggestion
For example, `^idx_{{table}}_{{column_list}}$` is a `template` where `{{table}}` is the table name and `{{column_list}}` is the list of the column name. So for index on `user(id, name)`, the legal name is `idx_user_id_name`.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-idx.md
> +Bytebase checks that all index names in DDL conform to naming conventions.
```suggestion
Bytebase checks that all index names in DDL conform to the naming conventions.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-uk.md
> +`Unique Key Naming Convention` uses `template` as format. Specifically, the `template` is an extended [regular expression](https://en.wikipedia.org/wiki/Regular_expression). The rest follows the rule
```suggestion
`Unique Key Naming Convention` uses `template` format. Specifically, the `template` is an extended [regular expression](https://en.wikipedia.org/wiki/Regular_expression). The rest follows the regular expression rules except the part with curly braces.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-uk.md
> +For example, `^uk_{{table}}_{{column_list}}$` is a `template` where `{{table}}` is the name of table and `{{column_list}}` is the list of the column name. So for unique key on `user(id, name)`, the l
```suggestion
For example, `^uk_{{table}}_{{column_list}}$` is a `template` where `{{table}}` is the table name and `{{column_list}}` is the list of the column name. So for unique key on `user(id, name)`, the legal name is `uk_user_id_name`.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-uk.md
> +Bytebase checks that all unique key names in DDL conform to naming conventions.
```suggestion
Bytebase checks that all unique key names in DDL conform to the naming conventions.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-fk.md
> +`Foreign Key Naming Convention` uses `template` as format. Specifically, the `template` is an extended [regular expression](https://en.wikipedia.org/wiki/Regular_expression). The rest follows the rul
```suggestion
`Foreign Key Naming Convention` uses `template` format. Specifically, the `template` is an extended [regular expression](https://en.wikipedia.org/wiki/Regular_expression). The rest follows the regular expression rules except the part with curly braces.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-fk.md
> +For example, `^fk_{{referencing_table}}_{{referencing_column}}_{{referenced_table}}_{{referenced_column}}$` is a `template` where `{{referencing_table}}` is the name of referencing table, `{{referenc
```suggestion
For example, `^fk_{{referencing_table}}_{{referencing_column}}_{{referenced_table}}_{{referenced_column}}$` is a `template` where `{{referencing_table}}` is the name of the referencing table, `{{referencing_column}}` is the list of the referencing column name, `{{referenced_table}}` is the name of the referenced table and `{{referenced_column}}` is the list of the referencing column name. So for unique key on `user(id, name)`, the legal name is `uk_user_id_name`.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/naming-index-fk.md
> +Bytebase checks that all foreign key names in DDL conform to naming conventions.
```suggestion
Bytebase checks that all foreign key names in DDL conform to the naming conventions.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/query-where-require.md
> +Bytebase considers this rule to be violated if the SQL has not WHERE clause.
```suggestion
Bytebase considers this rule to be violated if the SQL has no WHERE clause.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/table-require-pk.md
> +Bytebase considers this rule to be violated if the SQL try to create a no primary key table or drop the primary key. If the SQL drops all columns in the primary key, Bytebase also considers that this
```suggestion
Bytebase considers this rule to be violated if the SQL tries to create a no primary key table or drop the primary key. If the SQL drops all columns in the primary key, Bytebase also considers that this SQL drops the primary key.
```

2022-06-10 10:28 UTC, tianzhou commented on content/docs/en/features/schema-review/column-required.md
> +You can customize the columns you need.
```suggestion
You can customize which columns are required.
```

2022-06-13 03:16 UTC, rebelice commented
Updated and added a link to database-review-guide page in features/schema-review/oveview. PTAL @tianzhou

2022-06-13 03:30 UTC, tianzhou approved these changes
LGTM

2022-06-13 06:04 UTC, ecmadao approved these changes

2022-06-13 06:06 UTC, merged