chore: update blog feature image
bytebase/bytebase.com pull request #251
Opened 2022-06-14 10:03 UTC by milasuperstar

This is to update the blog "The Database as Code Landscape"s feature image so that sizing is friendlier for when we promote it on social media platforms.

Signed-off-by: Mila Wu <wumila1996@gmail.com>

2022-06-14 10:07 UTC, boojack submitted a review, later dismissed
LGTM. BTW if the old image file is no longer used, maybe you can delete it in the same PR.

2022-06-14 10:11 UTC, tianzhou commented
@milasuperstar could you please keep the original layout, but use 16:9? So that the image can be used in both the feature section and the content.

The layeredd stack is intentional. As the database is at the bottom

2022-06-14 10:12 UTC, tianzhou requested changes
Please see comments

2022-06-14 10:51 UTC, tianzhou requested changes

2022-06-14 10:51 UTC, tianzhou commented on content/blog/database-as-code-landscape.md
> +feature_image: /static/blog-assets/database-as-code-landscape/database-as-code-landscape-feature-image.webp
We can name it as `database-as-code-landscape`, so the content can also use it.

Also, let's put the image title on the top, otherwise, it's hard to read the text.

2022-06-15 02:42 UTC, tianzhou requested changes
Let's keep the 2022 suffix for the picture since it's bound to 2022. Save us some effort if we want to create a one

2022-06-15 05:48 UTC, tianzhou approved these changes
LGTM. Thanks for being patient. My fault in the first place that I used not that great image. Will hold the bar next time.

2022-06-15 05:49 UTC, merged