Feat/schema review policy
bytebase/bytebase.com pull request #252
Opened 2022-06-14 12:59 UTC by candy2255

PTAL

2022-06-14 14:32 UTC, tianzhou commented on content/blog/schema-review-policy-mysql.md
> +
For markdown, we just need to leave one empty line

2022-06-14 14:32 UTC, tianzhou commented on content/blog/schema-review-policy-mysql.md
> +A schema review policy is a set of SQL-style rules to check the SQL statement quality. DBAs can configure schema review policies for each environment. Bytebase will check SQL statements automatically
```suggestion
A schema review policy is a set of SQL-style rules to check the SQL statement quality. DBAs can configure schema review policies for each environment. Bytebase will check SQL statements automatically before executing schema changes, and block them if any configured policies are not met. 
```

2022-06-15 02:53 UTC, candy2255 commented on content/blog/schema-review-policy-mysql.md
> +
Got it. Done.

2022-06-15 04:19 UTC, tianzhou requested changes

2022-06-15 04:19 UTC, tianzhou commented on content/blog/schema-review-policy-mysql.md
> +
just need 1 empty line. Please also check the rest of articles.

2022-06-15 04:26 UTC, boojack commented
I just formated the content with https://codebeautify.org/markdown-formatter. FYI @candy2255

2022-06-16 10:07 UTC, candy2255 commented on content/blog/schema-review-policy-mysql.md
> +
Done.

2022-06-16 10:22 UTC, tianzhou approved these changes
LGTM

2022-06-17 08:52 UTC, merged