chore: improve docker installation
bytebase/bytebase.com pull request #255
Opened 2023-12-19 13:37 UTC by zll600

2023-12-20 02:55 UTC, rebelice commented
Need @zll600  for help to review

2023-12-21 02:59 UTC, h3n4l requested changes
Some comments

2023-12-21 02:59 UTC, h3n4l commented on content/docs/get-started/install/terminal-docker-run.md
> +docker run --init --publish 8080:8080 bytebase/bytebase:%%bb_version%%
We should remove the reset data hint on this page https://bytebase-com-git-dockerinstallation-bytebase.vercel.app/docs/get-started/step-by-step/deploy-with-docker/ if we remove the mount here.

2023-12-21 02:59 UTC, h3n4l commented on content/docs/get-started/self-host.md
> +        location /v1:adminExecute {
Can we combine these location directive entries?

2023-12-21 02:59 UTC, h3n4l commented on content/docs/get-started/self-host.md
> +**Note**: Because Bytebase need Websocket for some features. You also need to config NGINX to support websocket like above.
```suggestion
**Note**: Because Bytebase need WebSocket for some features, you also need to configure NGINX to support WebSocket like above.
```

2023-12-21 02:59 UTC, h3n4l commented on content/docs/get-started/self-host.md
> +#### Bytebase metadata persistent
```suggestion
#### Bytebase metadata persistence
```

2023-12-21 02:59 UTC, h3n4l commented on content/docs/get-started/install/terminal-docker-run.md
> +docker run --init --publish 8080:8080 bytebase/bytebase:%%bb_version%%
An alternative option is refer terminal-docker-run-volume.md
in  [bytebase-com-git-dockerinstallation-bytebase.vercel.app/docs/get-started/step-by-step/deploy-with-docker](https://bytebase-com-git-dockerinstallation-bytebase.vercel.app/docs/get-started/step-by-step/deploy-with-docker/)

2023-12-21 03:17 UTC, zll600 commented on content/docs/get-started/install/terminal-docker-run.md
> +docker run --init --publish 8080:8080 bytebase/bytebase:%%bb_version%%
I add a new file `terminal-docker-run-simple` only for `self-host`. If we need to update`quick-start`, we can do it separately?

2023-12-21 03:48 UTC, zll600 commented
@h3n4l PTAL

2023-12-21 04:44 UTC, h3n4l approved these changes
LGTM

2023-12-21 05:41 UTC, merged