feat: improve blog and changelog's rendering mechanism
bytebase/bytebase.com pull request #279
Opened 2022-06-23 10:24 UTC by Megrax

### Features
1. Override some default style provided by [@tailwindcss/typography](https://tailwindcss.com/docs/typography-plugin).
    - Remove rounding backticks of inline code and improve its style.

        | before | after |
        |:--:|:--:|
        | ![image](https://user-images.githubusercontent.com/56376387/175248529-e17aa952-b75c-45dc-878f-f5f7cf5c2c47.png) | ![image](https://user-images.githubusercontent.com/56376387/175249334-a82625c4-94ce-457e-adcc-711aec7a8a7a.png) |
    - Center images and fill the horizontal space.

        | before | after |
        |:--:|:--:|
        | ![image](https://user-images.githubusercontent.com/56376387/175249785-d472e181-4538-46d4-85ea-d4df80a88e57.png) | ![image](https://user-images.githubusercontent.com/56376387/175249943-a3c5d7e8-8cc8-4e52-b0b7-86b4ed7d372d.png) |
2. Add table of contents to blog/changelog page.

https://user-images.githubusercontent.com/56376387/175276292-7d3cc3a3-ff53-43b6-b4ea-f9db3b8eceb1.mp4

### Docs Change
- Change inline code to code block in changelog *Bytebase 1.0.4*.
    | before | after |
    |:--:|:--:|
    | ![image](https://user-images.githubusercontent.com/56376387/175277344-79ac5242-2832-4448-98e9-6d2a14d6ac29.png) | ![image](https://user-images.githubusercontent.com/56376387/175277191-a7794e53-8ce6-4933-ad34-3b3ef795400d.png) |

2022-06-23 10:30 UTC, tianzhou commented on content/changelog/bytebase-1-0-4.md
> +User can install `bb` CLI with only one command.
let's create a separate PR for this

2022-06-23 10:31 UTC, tianzhou commented
![CleanShot 2022-06-23 at 18 31 12](https://user-images.githubusercontent.com/230323/175279157-b699cfd2-257c-46dc-a3df-a61be4f87ffb.png)

The Toc has a vertical scroll bar

2022-06-23 10:34 UTC, Megrax commented
> Is this still WIP?

@tianzhou Yes, currently there's a bug in [our blog site](https://www.bytebase.com/blog/database-as-code-landscape/#prisma). Maybe we should merge after this bug is fixed.

https://user-images.githubusercontent.com/56376387/175279322-21a6eaad-16d2-4a58-b6e7-98010fa55e69.mp4

2022-06-23 10:36 UTC, Megrax commented on content/changelog/bytebase-1-0-4.md
> +User can install `bb` CLI with only one command.
OK, I'll create one later. I did it here because the inline code is too long and overlaps with the TOC.

2022-06-24 05:12 UTC, Megrax commented on content/changelog/bytebase-1-0-4.md
> +User can install `bb` CLI with only one command.
Done in #287

2022-06-24 07:41 UTC, tianzhou commented
Is this ready now?

2022-06-24 07:45 UTC, Megrax commented
> Is this ready now?

Yes. BTW please check if the vertical scroll bar still exists in the latest preview. (I cannot reproduce this bug maybe because I don't have a large display.)

2022-06-24 07:50 UTC, tianzhou commented
> > Is this ready now?
> 
> Yes. BTW please check if the vertical scroll bar still exists in the latest preview. (I cannot reproduce this bug maybe because I don't have a large display.)

The vertical scroll bar issue is fixed.

2022-06-24 07:52 UTC, tianzhou commented on components/Toc.vue
> +    /**
Looks like it only jumps on the first level title, is it possible to jump on the second level title as well. 

Take this as an example
https://bytebase-com-git-feat-update-blog-changelog-ren-1a8f4f-bytebase.vercel.app/blog/database-as-code-landscape

2022-06-24 08:13 UTC, boojack commented
When I scroll very fast, the TOC doesn't stop on the correct item. Expect: the `The Overview` should be highlight.

![image](https://user-images.githubusercontent.com/24653555/175492663-5a7548f9-5e91-41be-b8a6-d6af898df8ca.png)

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/24653555/175493361-b30bb571-60c0-4e29-a200-c3fb741fafff.png">

2022-06-24 08:52 UTC, Megrax commented on components/Toc.vue
> +    /**
The current design is that all `<h2>` and `<h3>` titles will be list in the TOC and you can jump to the section by click on the title.
For example:

<img width="300" src="https://user-images.githubusercontent.com/56376387/175491161-f443175e-826e-4ecd-908c-ce0a16cff7a8.png" />

You can jump to both `The Gatekeepers` or `Liquibase`. There're two levels.

2022-06-24 08:54 UTC, boojack requested changes

2022-06-24 08:54 UTC, boojack commented on components/Toc.vue
> +        const Ids = titles.map((t) => t.id);
rename to `hashIds`?

2022-06-24 08:54 UTC, boojack commented on components/Toc.vue
> +    class="hidden xl:flex flex-col justify-start items-start sticky w-52 top-0 right-6 2xl:right-10 pr-4 h-full max-h-screen flex-shrink-0 overflow-x-hidden overflow-y-auto text-sm"
`hidden xl:flex` is basing on window width not the container, so it will causes TOC hidden in the document with a normal width.

|before | after|
|-|-|
|<img width="1200" alt="image" src="https://user-images.githubusercontent.com/24653555/175500158-12cd636a-52dc-468e-bc59-fd39da043cb5.png">|<img width="1206" alt="image" src="https://user-images.githubusercontent.com/24653555/175499623-38f7b465-39d6-48a3-8d04-749dc737eae2.png">|

2022-06-24 08:54 UTC, boojack commented on components/Toc.vue
> +    const titlesShouldList = computed(() =>
This name `titlesShouldList` looks a bit weird, how about `tocList`?

2022-06-24 08:55 UTC, tianzhou commented on components/Toc.vue
> +    /**
Yes, but when we use scroller, it only anchors on the <h2>, not on the <h3>

2022-06-24 09:09 UTC, boojack commented on components/Toc.vue
> +    /**
Works correctly for me

![image](https://user-images.githubusercontent.com/24653555/175503089-81a7569d-7f1f-48d4-acb1-bf2ab8ecd896.png)

2022-06-24 09:17 UTC, tianzhou commented on components/Toc.vue
> +    /**
Just checked with @boojack , looks like we encounter the same issue. it can anchor on h3, just not that reliably when scrolling too fast.

2022-06-24 09:21 UTC, Megrax commented
> When I scroll very fast, the TOC doesn't stop on the correct item. Expect: the `The Overview` should be highlight.
> 
> ![image](https://user-images.githubusercontent.com/24653555/175492663-5a7548f9-5e91-41be-b8a6-d6af898df8ca.png)
> 
> <img alt="image" width="1449" src="https://user-images.githubusercontent.com/24653555/175493361-b30bb571-60c0-4e29-a200-c3fb741fafff.png">

This is probably a problem caused by IO (IntersectionObserver) itself. There's a related [discussion](https://stackoverflow.com/questions/61951380/intersection-observer-fails-sometimes-when-i-scroll-fast) here. Because IO is a browser provided api, the browser will help handle the firing procedure. So if you scroll too fast, the change may not be accurately detected.

2022-06-24 09:27 UTC, Megrax commented on components/Toc.vue
> +    /**
If this kind of accuracy is that essential in this situation, it may be hard to implement a TOC relying on IO. Maybe the old onScroll solution should be taken into consideration again. In my personal opinion, this is acceptable though.

2022-06-24 09:28 UTC, boojack commented
> This is probably a problem caused by IO (IntersectionObserver) itself. There's a related [discussion](https://stackoverflow.com/questions/61951380/intersection-observer-fails-sometimes-when-i-scroll-fast) here. Because IO is a browser provided api, the browser will help handle the firing procedure. So if you scroll too fast, the change may not be accurately detected.

Can we add a scroll listener to ensure that stop on the correct item?

2022-06-24 09:38 UTC, Megrax commented
> Can we add a scroll listener to ensure that stop on the correct item?

I guess so, but then it makes no sense to continue using IO anymore :(

2022-06-24 09:41 UTC, boojack commented
> I guess so, but then it makes no sense to continue using IO anymore :(

The wrong position looks a bit bad:( So let's roll back to scroll listener.

2022-06-27 12:04 UTC, Megrax commented
PTAL @boojack @tianzhou

2022-06-27 13:47 UTC, boojack approved these changes
LGTM. I pushed a commit that uses an override class instead of "break-point": https://github.com/bytebase/bytebase.com/pull/279/commits/642098a59b09c35760dfab9a9e43ec1a9f344564

2022-06-27 16:44 UTC, tianzhou approved these changes
LGTM

2022-06-27 16:44 UTC, merged