docs: add PITR backup and restore operations
bytebase/bytebase.com pull request #290
Opened 2022-06-28 07:52 UTC by dragonly

2022-06-28 08:34 UTC, dragonly commented on content/docs/en/operating/disaster-recovery.md
> +# Point-in-time Recovery for MySQL
Fixed.

2022-06-28 08:44 UTC, boojack submitted a review, later dismissed
LGTM.

2022-06-28 10:49 UTC, tianzhou requested changes

2022-06-28 10:49 UTC, tianzhou commented on content/docs/en/operating/disaster-recovery.md
> +It’s recommended to follow the [doc for backup](/docs/use-bytebase/backup-restore-database/backup) to set up automatic backups. Bytebase will check that an instance meeds all the prerequisites and au
```suggestion
It’s recommended to follow the [doc for backup](/docs/use-bytebase/backup-restore-database/backup) to set up automatic backups. Bytebase will check that an instance meets all the prerequisites and automatically archives binlog files.
```
```suggestion
It’s recommended to follow the [doc for backup](/docs/use-bytebase/backup-restore-database/backup) to set up automatic backups. Bytebase will check that an instance meeds all the prerequisites and automatically archives binlog files.
```

2022-06-28 10:49 UTC, tianzhou commented on content/docs/en/operating/disaster-recovery.md
> +After PITR is done, the current database will be restored to the state before but not including the target time. For example, if you give the restore time 10:00:00, Bytebase would recover the databas
```suggestion
PITR restores the database to the state right before the target time. For example, if you give the restore time 10:00:00, Bytebase would recover the database to the state just after 9:59:59 passed but before 10:00:00.
```
```suggestion
After PITR is done, the current database will be restored to the state before but not including the target time. For example, if you give the restore time 10:00:00, Bytebase would recover the database to the state just after 9:59:59 passed but before 10:00:00.
```

2022-06-28 10:49 UTC, tianzhou commented on content/docs/en/operating/disaster-recovery.md
> +The second task is called Swap. It will swap the recovered temporary database with your current database. After the Swap task, your current database will be at the state of the point in time you chos
```suggestion
The second task is called Swap. It will swap the restored temporary database with your current database. After the Swap task, your current database will be at the state of the point in time you chose to restore, and the original database will be renamed by appending a timestamp (the issue created time) and an _old suffix. You could check the old database and use the data or just delete it to save storage space.
```
```suggestion
The second task is called Swap. It will swap the recovered temporary database with your current database. After the Swap task, your current database will be at the state of the point in time you chose to restore, and the original database will be renamed by appending a timestamp (the issue created time) and an _old suffix. You could check the old database and use the data or just delete it to save storage space.
```

2022-06-28 10:49 UTC, tianzhou commented on content/docs/en/operating/disaster-recovery.md
> +Note that you must stop ongoing queries on the current database before approving the Swap task.
maybe use "should" instead of "must"?

Also consider using "hint" block? https://www.bytebase.com/docs/document-write-guide#hint

2022-06-28 10:49 UTC, tianzhou commented on content/docs/en/operating/disaster-recovery.md
> +Now you successfully performed a Point-in-time Recovery to your database!
```suggestion
Now you have successfully performed a Point-in-time Recovery to your database!
```

2022-06-28 10:49 UTC, tianzhou commented on content/docs/en/operating/disaster-recovery.md
> +## General Disaster Recovery Operations
I would put this first since PITR content is long and more specific

2022-06-29 05:28 UTC, tianzhou approved these changes
LGTM

2022-06-29 05:35 UTC, dragonly commented
PTAL @candy2255 @adela-bytebase

2022-06-30 05:41 UTC, candy2255 approved these changes
LGTM

2022-06-30 07:48 UTC, dragonly commented
Let's hold and wait for the next release.

2022-07-07 10:03 UTC, merged