docs: add blog for installing mysql shell on mac
bytebase/bytebase.com pull request #293
Opened 2022-06-30 03:56 UTC by milasuperstar

Signed-off-by: Mila Wu <wumila1996@gmail.com>

2022-06-30 04:00 UTC, boojack submitted a review, later dismissed
Some output shouldn't use `bash` prefix.

2022-06-30 05:12 UTC, tianzhou requested changes

2022-06-30 05:12 UTC, tianzhou commented on content/blog/how-to-install-mysql-shell-on-macos.md
> +You can install MySQL Shell on your Mac by using one of these two ways: with the help of Homebrew or to install using the MySQL Shell package.
```suggestion
You can install MySQL Shell on your Mac by using Homebrew or the official MySQL Shell package.
```

2022-06-30 05:12 UTC, tianzhou commented on content/blog/how-to-install-mysql-shell-on-macos.md
> +### Installing MySQL Shell
```suggestion
### Install MySQL Shell
```

2022-06-30 05:12 UTC, tianzhou commented on content/blog/how-to-install-mysql-shell-on-macos.md
> +
Need to add the command to verify the installation

2022-06-30 05:12 UTC, tianzhou commented on content/blog/how-to-install-mysql-shell-on-macos.md
> +mysqlsh
Ok, I guess there is a misunderstading, and my bad...

What I initially meant is to install https://dev.mysql.com/doc/refman/8.0/en/mysql.html, the MySQL Command-Line Client. Shell is usually an interchangeable word with the MySQL CLI.

Clearly that's not the case for MySQL

2022-06-30 05:12 UTC, tianzhou commented on content/blog/how-to-install-mysql-shell-on-macos.md
> +feature_image: /static/blog/how-to-install-mysql-shell-on-macos/mysql-mac.webp
the image file name is mysql-mac.webp.webp

2022-06-30 10:35 UTC, tianzhou requested changes

2022-06-30 10:35 UTC, tianzhou commented on content/blog/how-to-install-mysql-shell-on-macos.md
> +MySQL Shell is an interactive JavaScript, Python, or SQL interface for MySQL Server and is a component that you can install separately. It can be installed on your Mac by using Homebrew or the offici
```suggestion
[MySQL Shell](https://dev.mysql.com/doc/mysql-shell/8.0/en/) is an interactive JavaScript, Python, or SQL interface for MySQL Server and is a component that you can install separately. It can be installed on your Mac by using Homebrew or the official MySQL Shell package.
```

2022-06-30 10:35 UTC, tianzhou commented on content/blog/how-to-install-mysql-shell-on-macos.md
> +MySQL Shell is an interactive JavaScript, Python, or SQL interface for MySQL Server and is a component that you can install separately. It can be installed on your Mac by using Homebrew or the offici
Let's add a paragraph to mention not be confused with the MySQL Command-Line Client https://dev.mysql.com/doc/refman/8.0/en/mysql.html

Since we made the mistake.

2022-07-04 05:48 UTC, tianzhou approved these changes
LGTM

2022-07-04 06:06 UTC, merged