docs: data query and export
bytebase/bytebase.com pull request #31
Opened 2023-05-22 06:53 UTC by boojack

2023-05-22 07:39 UTC, adela-bytebase requested changes

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-export.md
> +1. Go to the home page or project list page, and click the `Export data` button.
```suggestion
1. Go to the home page or project list page, and click **Export data**.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-export.md
> +3. Click the `Create` button to submit the request.
```suggestion
3. Click **Create** to submit the request.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-export.md
> +4. After the request is approved, click the `Export` button to export the data.
```suggestion
4. After the request is approved, click **Export** to export the data.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-query.md
> +1. Go to the home page or project list page, and click the `Request query` button.
```suggestion
1. Go to the home page or project list page, and click **Request query**.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-export.md
> +As a project owner, you can go to the project member management page and manually add the role of data exporter.
```suggestion
As a **Project Owner**, you can go to the project, click **Settings**, find the **Management members** section, and manually add the role of **Project Exporter**.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-export.md
> +Before adding the data exporter role, you need to add the data querier role first to ensure that the user has the permission to query the data.
```suggestion
Before adding the **Project Exporter** role, you need to add the **Project Querier** role first to ensure that the user has permission to query the data.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-export.md
> +Once the data exporter role is added, the user can export the query result of the specified database in SQL Editor.
```suggestion
Once the **Project Exporter** role is added, the user can export the query result of the specified database in SQL Editor.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-export.md
> +In Enterprise plan, users need to apply for data exporter role before exporting data for data security governance.
```suggestion
In Enterprise plan, users need to apply for **Project Exporter** role before exporting data for data security governance.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/data-query-and-export/data-query.md
> +3. Click the `Create` button to submit the request.
```suggestion
3. Click **Create** to submit the request.
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/_layout.md
> +## Data query and export
```suggestion
## Data Query and Export
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/_layout.md
> +### [Data query approval flow](/data-query-and-export/data-query)
```suggestion
### [Data Query Approval Flow](/data-query-and-export/data-query)
```

2023-05-22 07:39 UTC, adela-bytebase commented on content/docs/_layout.md
> +### [Data export approval flow](/data-query-and-export/data-export)
```suggestion
### [Data Export Approval Flow](/data-query-and-export/data-export)
```

2023-05-22 08:26 UTC, tianzhou approved these changes
LGTM

2023-05-24 13:48 UTC, tianzhou approved these changes
LGTM

2023-05-24 13:49 UTC, merged