Add the blog post for PITR
bytebase/bytebase.com pull request #329
Opened 2022-07-11 07:49 UTC by candy2255

2022-07-11 08:10 UTC, dragonly reviewed
To be consistent with the pictures.

2022-07-11 08:10 UTC, dragonly commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Let’s say there is a MySQL database “db_pitr_example” that has two tables “tb_pitr_one” and “tb_pitr_two”.
```suggestion
Let’s say there is a MySQL database “db_pitr_example” that has two tables “pitr_one” and “pitr_two”. 
```

2022-07-11 08:10 UTC, dragonly commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Suddenly, an application goes down since someone accidentally deletes the table “tb_pitr_two”. Then, the DBA or the on-call developer needs to restore that deleted table.
```suggestion
Suddenly, an application goes down since someone accidentally deletes the table “pitr_two”. Then, the DBA or the on-call developer needs to restore that deleted table.
```

2022-07-11 08:10 UTC, dragonly commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Let’s verify tables in the database “db_pitr_example”. The deleted table “tb_pitr_two” is back again.
```suggestion
Let’s verify tables in the database “db_pitr_example”. The deleted table “pitr_two” is back again.
```

2022-07-11 09:12 UTC, tianzhou requested changes

2022-07-11 09:12 UTC, tianzhou commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Bytebase is an open-source database DevOps tool, and it’s the GitLab for managing databases throughout the application development lifecycle. It offers a web-based workspace for DBAs and Developers t
```suggestion
Bytebase is an open source database DevOps tool, it's the GitLab for managing databases throughout the software development lifecycle (SDLC). It offers a web-based workspace for Developers and DBAs to collaborate and execute database changes safely and efficiently. 
```

2022-07-11 09:12 UTC, tianzhou commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Bytebase is an open-source database DevOps tool, and it’s the GitLab for managing databases throughout the application development lifecycle. It offers a web-based workspace for DBAs and Developers t
FYI, I also updated our internal marketing doc.

2022-07-11 09:12 UTC, tianzhou commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +What would you do if you encountered these scenarios in your daily work?
```suggestion
As an application developer, what would you do if you encountered these scenarios in your daily work?
```

2022-07-11 09:12 UTC, tianzhou commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +The last step means Bytebase is doing an in-place database recovery and does not require application code change.
```suggestion
The last step means Bytebase is doing an in-place database recovery and does not require any application code change.
```

2022-07-11 09:12 UTC, tianzhou commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Suddenly, an application goes down since someone accidentally deletes the table “pitr_two”. Then, the DBA or the on-call developer needs to restore that deleted table.
```suggestion
Suddenly, the application goes down since someone accidentally deletes the table “pitr_two”. Then, the DBA or the on-call developer needs to restore that deleted table.
```

2022-07-11 09:12 UTC, tianzhou commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +For MySQL, this means you would look for the valid backup and the relevant binlog files to recover to a point in the past before the incident occurred. This is a complicated process that requires an
```suggestion
For MySQL, this means you would look for the valid backup and the relevant binlog files to recover to a point in the past before the incident occurred. This is a complicated process that requires an experienced DBA to operate. Today, we are introducing Point-in-Time Recovery (PITR) Beta in Bytebase, which enables users to perform this error-prone operation with just a few clicks.
```

2022-07-11 09:12 UTC, tianzhou commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +We just showed you how Bytebase performs a point-in-time recovery. It’s an in-place recovery, which means it does not require extra work to change the application code after the recovery. To learn mo
This link is broken

2022-07-11 09:12 UTC, tianzhou commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Let’s say there is a MySQL database “db_pitr_example” that has two tables “pitr_one” and “pitr_two”.
For places using double quotes, shall we use backticks like `db_pitr_example` to highlight?

@adela-bytebase

2022-07-12 05:43 UTC, adela-bytebase commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Let’s say there is a MySQL database “db_pitr_example” that has two tables “pitr_one” and “pitr_two”.
yes, let's use inline code

2022-07-12 06:19 UTC, adela-bytebase commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +**Step1**. Click the button “Restore to point in time” in the tab ”Backup and Restore”.
Labels like “Restore to point in time” should be bold.

2022-07-12 06:20 UTC, adela-bytebase commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +**Step1**. Click the button “Restore to point in time” in the tab ”Backup and Restore”.
also ”Backup and Restore”

2022-07-12 07:35 UTC, candy2255 commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +**Step1**. Click the button “Restore to point in time” in the tab ”Backup and Restore”.
Done

2022-07-12 07:35 UTC, candy2255 commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +Let’s say there is a MySQL database “db_pitr_example” that has two tables “pitr_one” and “pitr_two”.
Done

2022-07-12 09:40 UTC, tianzhou submitted a review, later dismissed
LGTM

2022-07-12 10:02 UTC, adela-bytebase commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +**Step1**. Click the button **Restore to point in time** in the tab **Backup and restore**.
remove "button", "tab" when you mention the label on it.

2022-07-12 10:05 UTC, adela-bytebase commented on content/blog/restoring-a-mysql-database-to-a-point-in-time.md
> +**Step1**. Click the button **Restore to point in time** in the tab **Backup and restore**.
**Step1**. Click **Restore to point in time** under **Backup and restore**.

2022-07-12 14:21 UTC, tianzhou approved these changes
LGTM

2022-07-12 14:21 UTC, merged