feat: gh-ost integration user doc
bytebase/bytebase.com pull request #344
Opened 2022-07-14 09:24 UTC by RainbowDashy

2022-07-14 14:19 UTC, tianzhou requested changes

2022-07-14 14:19 UTC, tianzhou commented on content/docs/en/_layout.md
> +## [gh-ost Integration](/gh-ost-integration)
Let's put this under "Change Database" section, after "Migration History"

And use title "Online Schema Migration for MySQL"

2022-07-14 14:19 UTC, tianzhou commented on content/docs/en/gh-ost-integration.md
> +gh-ost is a triggerless online schema migration tool for MySQL.
let's add a link to the gh-ost github project page

2022-07-14 14:19 UTC, tianzhou commented on content/docs/en/gh-ost-integration.md
> +Bytebase uses the power of gh-ost to help users migrate MySQL databases with little downtime.
```suggestion
Bytebase leverages gh-ost to migrate MySQL table schemas with little downtime.
```

2022-07-14 14:19 UTC, tianzhou commented on content/docs/en/gh-ost-integration.md
> +This is currently a preview feature. Data loss is possible.
```suggestion
This is currently a preview feature.
```

2022-07-14 14:19 UTC, tianzhou commented on content/docs/en/gh-ost-integration.md
> +This is currently a preview feature. Data loss is possible.
Let's move this to the top

2022-07-14 14:19 UTC, tianzhou commented on content/docs/en/gh-ost-integration.md
> +- Bytebase currently only supports migrating on main.
This is not clear

2022-07-14 14:19 UTC, tianzhou commented on content/docs/en/gh-ost-integration.md
> +- Foreign key constraints are not supported.
Should this be put under Requirement as well?

2022-07-14 14:19 UTC, tianzhou commented on content/docs/en/gh-ost-integration.md
> +To find the UNIX socket file, we must acquire the database id and task id.
Use "you" instead of "we" across the article.

2022-07-15 07:46 UTC, dragonly reviewed
LG otherwise.

2022-07-15 07:46 UTC, dragonly commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +1. Finally, at the right time, they replace your original table with the ghost table.
```suggestion
1. Finally, they replace your original table with the ghost table at the right time.
```

2022-07-15 07:46 UTC, dragonly commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +- Bytebase currently only supports migrating on primary.
```suggestion
- Bytebase currently only supports migrating on the primary.
```

2022-07-15 07:46 UTC, dragonly commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +Click “Alter Schema” on the database page.
```suggestion
Click "Alter Schema" on the database page.
```
Let's use the straight quote mark `"` for consistency with other docs.

2022-07-15 07:46 UTC, dragonly commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +Make sure that the gh-ost sync task check is passing. Then click “Approve” to run the sync task
```suggestion
Make sure that the gh-ost sync task check is passing. Then click “Approve” to run the sync task.
```

2022-07-15 07:46 UTC, dragonly commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +To find the UNIX socket file, you have to acquire the database id and task id.
```suggestion
To find the UNIX socket file, you must acquire the database and task id.
```

2022-07-15 07:57 UTC, dragonly submitted a review, later dismissed

2022-07-15 08:13 UTC, tianzhou approved these changes
LGTM

2022-07-15 08:13 UTC, tianzhou commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +[gh-ost](https://github.com/github/gh-ost) is a triggerless online schema migration tool for MySQL.
```suggestion
[gh-ost](https://github.com/github/gh-ost) is a triggerless online schema migration tool for MySQL. Bytebase leverages gh-ost to migrate MySQL table schemas with little downtime.
```

2022-07-15 08:13 UTC, tianzhou commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +Bytebase leverages gh-ost to migrate MySQL table schemas with little downtime.
this can be removed now as it moved to the first line

2022-07-15 08:18 UTC, RainbowDashy commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +[gh-ost](https://github.com/github/gh-ost) is a triggerless online schema migration tool for MySQL.
Done

2022-07-15 08:18 UTC, RainbowDashy commented on content/docs/en/change-database/online-schema-migration-for-mysql.md
> +Bytebase leverages gh-ost to migrate MySQL table schemas with little downtime.
Done

2022-07-15 08:23 UTC, tianzhou approved these changes
LGTM

2022-07-21 09:48 UTC, d-bytebase approved these changes

2022-07-21 09:49 UTC, merged