blog: Dev, SRE, Operations, DevOps - What’s the Difference
bytebase/bytebase.com pull request #348
Opened 2022-07-15 10:59 UTC by tianzhou

2022-07-15 13:36 UTC, milasuperstar commented on content/blog/dev-sre-ops-devops-difference.md
> +1. No longer deal with physical equipment, this part is taken care of by the cloud services.
```suggestion
1. No longer deals with physical equipment, this part is taken care of by the cloud services.
```

2022-07-15 13:36 UTC, milasuperstar commented on content/blog/dev-sre-ops-devops-difference.md
> +Developers (Dev), Site Reliability Engineer (SRE), and Operations (Ops) are job types, while DevOps is a system. If we take a soccer analogy, Dev, SRE, and Ops correspond to positions like forward, m
love the analogy lol now i really understand devops 😂

2022-07-15 13:41 UTC, milasuperstar commented
BTW, the image size looks a bit off on the blog site, i feel like sth like 20:9 or 2:1 would look better
<img width="450" alt="Screen Shot 2022-07-15 at 21 31 50" src="https://user-images.githubusercontent.com/72733948/179234467-56bd460e-762b-4019-a6ae-51225ed47f29.png">

2022-07-15 15:38 UTC, tianzhou commented on content/blog/dev-sre-ops-devops-difference.md
> +1. No longer deal with physical equipment, this part is taken care of by the cloud services.
Done

2022-07-15 15:38 UTC, tianzhou commented
> BTW, the image size looks a bit off on the blog site, i feel like sth like 20:9 or 2:1 would look better <img alt="Screen Shot 2022-07-15 at 21 31 50" width="450" src="https://user-images.githubusercontent.com/72733948/179234467-56bd460e-762b-4019-a6ae-51225ed47f29.png">

Changed to 2:1 ratio

2022-07-15 15:39 UTC, tianzhou commented
PTAL

2022-07-16 01:54 UTC, candy2255 approved these changes
LGTM

2022-07-16 02:49 UTC, milasuperstar submitted a review, later dismissed

2022-07-18 03:22 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +Also called IT Operations, Production Engineer (PE), or simply Operations (Ops)。They are responsible for data center management, machine installation, network wiring, monitoring, and alerting. In the
Also called IT Operations, Production Engineer (PE), or simply Operations (Ops)。标点符号改成英文状态 .

2022-07-18 03:29 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +Developers (Dev), Site Reliability Engineer (SRE), and Operations (Ops) are job types, while DevOps is a system. If we take a soccer analogy, Dev, SRE, and Ops correspond to positions like forward, m
DevOps is a formation like 4-3-3.  这句话后面可以加一点解释吗，对于不懂足球的人来说可能会有疑惑

2022-07-18 03:36 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +Site Reliability Engineer (SRE), coined by Google in 2003. A couple of backgrounds contributes to its birth:
from “A couple of backgrounds contributes to its birth” to “SRE is created under the following backgrounds"

2022-07-18 03:38 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1 and 2 prompted the need for a specialized job function, of which 2 also serves to balance the development pace (please do not break that much), while 3 provides the labor supply for SRE. Since SRE’
thus it’s a natural transition for Operations to move into an SRE role 
前面已经有 since 了，thus 可以删除

2022-07-18 03:39 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. No longer deals with physical equipment, this part is taken care of by the cloud services.
SRE no longer deals with physical equipment which is taken care of by the cloud services.

2022-07-18 03:43 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. No longer deals with physical equipment, this part is taken care of by the cloud services.
下面的两条background前面都可以加上主语SRE，变成一句完整的句子

2022-07-18 03:44 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Stronger engineering background. Some SREs possess quite strong engineering skills. e.g. The author of the monitoring software Prometheus, who was an SRE at Google.
from “e.g. The author of the monitoring software Prometheus, who was an SRE at Google.” to “For example, the author of the monitoring software Prometheus was an SRE at Google."

2022-07-18 06:09 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +DevOps is a system. As just mentioned, there is no intersection between Dev and Ops work, DevOps is to combine these 2 work types together. More precisely, it is to let Dev take on the Ops work. Unde
```suggestion
DevOps is a system. As just mentioned, there is no intersection between Dev and Ops work, while DevOps is to combine these 2 work types together. More precisely, DevOps is to let Dev take on the Ops work. Under DevOps, there is no traditional Ops role, and the Ops responsibility may be shared by Dev and SRE, or the work may be carried out by Dev alone. This further eliminates the SRE role.
```

2022-07-18 06:12 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Confused about whether DevOps is a system or a job function. This depends on the context. Initially, DevOps represented the system combining Dev and Ops work. This system may have both Dev and SRE
In the latter case 不太知道指代的是什么

2022-07-18 06:13 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Stronger engineering background. Some SREs possess quite strong engineering skills. e.g. The author of the monitoring software Prometheus, who was an SRE at Google.
```suggestion
1. Stronger engineering background. Some SREs possess quite strong engineering skills. For example, the author of the monitoring software Prometheus was an SRE at Google.
```

2022-07-18 06:14 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. No longer deals with physical equipment, this part is taken care of by the cloud services.
```suggestion
1. SRE no longer deals with physical equipment which is taken care of by the cloud services.
```

2022-07-18 06:15 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1 and 2 prompted the need for a specialized job function, of which 2 also serves to balance the development pace (please do not break that much), while 3 provides the labor supply for SRE. Since SRE’
```suggestion
1 and 2 prompted the need for a specialized job function, of which 2 also serves to balance the development pace (please do not break that much), while 3 provides the labor supply for SRE. Since SRE’s main responsibility is to ensure service stability, it’s a natural transition for Operations to move into an SRE role.
```

2022-07-18 06:17 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +Site Reliability Engineer (SRE), coined by Google in 2003. A couple of backgrounds contributes to its birth:
```suggestion
Site Reliability Engineer (SRE), coined by Google in 2003. The following factors contribute to the birth of this role:
```

2022-07-18 06:18 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +Also called IT Operations, Production Engineer (PE), or simply Operations (Ops)。They are responsible for data center management, machine installation, network wiring, monitoring, and alerting. In the
```suggestion
Also called IT Operations, Production Engineer (PE), or simply Operations (Ops). They are responsible for data center management, machine installation, network wiring, monitoring, and alerting. In the early days, a large amount of the operations’ work is to deal with physical equipment. This work requires a lot of manual intervention and is risky. In the last 10 years, as Cloud services gradually replace the physical data center, the traditional operations workload has been significantly reduced, and the pure Ops job ceases to exist.
```

2022-07-18 07:40 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +Developers (Dev), Site Reliability Engineer (SRE), and Operations (Ops) are job types, while DevOps is a system. If we take a soccer analogy, Dev, SRE, and Ops correspond to positions like forward, m
Some explanation about 4-3-3 formation may be needed here, as this could be confusing to someone who is not familiar with football.

2022-07-18 07:46 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Confused about whether DevOps is a system or a job function. This depends on the context. Initially, DevOps represented the system combining Dev and Ops work. This system may have both Dev and SRE
not sure about what "in the latter case" refers to

2022-07-18 07:54 UTC, tianzhou reviewed
PTAL

2022-07-18 07:54 UTC, tianzhou commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Confused about whether DevOps is a system or a job function. This depends on the context. Initially, DevOps represented the system combining Dev and Ops work. This system may have both Dev and SRE
Refined

2022-07-18 09:58 UTC, milasuperstar requested changes

2022-07-18 09:58 UTC, milasuperstar commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Stronger engineering background. Some SREs possess quite strong engineering skills. For example, the author of the monitoring software Prometheus was an SRE at Google.
```suggestion
1. Stronger engineering background. Some SREs possess quite strong engineering skills. For example, the creator of the monitoring software [Prometheus](https://prometheus.io/) was an SRE at Google.
```

2022-07-18 09:58 UTC, milasuperstar commented on content/blog/dev-sre-ops-devops-difference.md
> +DevOps is a system. As just mentioned, there is no intersection between Dev and Ops work, while DevOps is to combine these 2 work types together. More precisely, DevOps is to let Dev take on the Ops
```suggestion
DevOps is a system. As just mentioned, there is no intersection between Dev and Ops work, while DevOps is to combine these two work types together. More precisely, DevOps is to let Dev take on the Ops work. Under DevOps, there is no traditional Ops role, and the Ops responsibility may be shared by Dev and SRE, or the work may be carried out by Dev alone. This further eliminates the SRE role.
```

2022-07-19 01:52 UTC, tianzhou commented
PTAL

2022-07-19 01:58 UTC, milasuperstar submitted a review, later dismissed

2022-07-19 02:02 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Traditional Operations need to transition to a new role.
```suggestion
1. Traditional Ops need to transition to a new role.
```

2022-07-19 02:03 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1 and 2 prompted the need for a specialized job function, of which 2 also serves to balance the development pace (please do not break that much), while 3 provides the labor supply for SRE. Since SRE’
```suggestion
1 and 2 prompted the need for a specialized job function, of which 2 also serves to balance the development pace (please do not break that much), while 3 provides the labor supply for SRE. Since SRE’s main responsibility is to ensure service stability, it’s a natural transition for Ops to move into an SRE role.
```

2022-07-19 02:03 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +Simply put, SRE is an upgraded version of traditional Operations. SRE differs from Operations in the following ways:
```suggestion
Simply put, SRE is an upgraded version of traditional Ops. SRE differs from Ops in the following ways:
```

2022-07-19 02:04 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Employs a more systematic approach to ensure service stability, such as building automation tools, and working with the development team together to develop [Service Level Objective (SLO)](https:/
```suggestion
1. SRE employs a more systematic approach to ensure service stability, such as building automation tools, and working with the development team together to develop [Service Level Objective (SLO)](https://en.wikipedia.org/wiki/Service-level_objective) / [Service Level Agreement (SLA)](https://en.wikipedia.org/wiki/Service-level_agreement) / [Service Level Indicator (SLI)](https://en.wikipedia.org/wiki/Service_level_indicator). This triplet serves as the contract between SREs and Developers to work towards a shared goal of providing a better service.
```

2022-07-19 02:04 UTC, Gracemei commented on content/blog/dev-sre-ops-devops-difference.md
> +1. Stronger engineering background. Some SREs possess quite strong engineering skills. For example, the creator of the monitoring software [Prometheus](https://prometheus.io/) was an SRE at Google.
```suggestion
1. SRE has stronger engineering background. Some SREs possess quite strong engineering skills. For example, the creator of the monitoring software [Prometheus](https://prometheus.io/) was an SRE at Google.
```

2022-07-19 04:19 UTC, tianzhou commented
PTAL

2022-07-19 05:04 UTC, Gracemei approved these changes

2022-07-19 06:50 UTC, merged