chore: supabase edits
bytebase/bytebase.com pull request #355
Opened 2024-07-08 16:47 UTC by awalias

updates language around Supabase's postgres compatibility (see: https://github.com/supabase/postgres), and adds Hipaa compliance a la https://supabase.com/security

2024-07-08 16:56 UTC, tianzhou requested changes
One comment. Otherwise LGTM.

2024-07-08 16:56 UTC, tianzhou commented on content/blog/neon-vs-supabase.md
> +If you want 100% Postgres compatibility or are looking to build a full-stack application, Supabase has everything
https://supabase.com/docs/guides/database/postgres/roles-superuser

99% or even 99.9% is fine, however, saying it 100% misses the mark as compared with self-hosted PG.

2024-07-08 22:10 UTC, awalias commented on content/blog/neon-vs-supabase.md
> +If you want 100% Postgres compatibility or are looking to build a full-stack application, Supabase has everything
ah that's an interesting point, it's probably a matter of definition but no worries I will reformulate 👍

2024-07-08 22:12 UTC, awalias commented on content/blog/neon-vs-supabase.md
> +If you want 100% Postgres compatibility or are looking to build a full-stack application, Supabase has everything
```suggestion
If you're looking for a dedicated Postgres instance or are looking to build a full-stack application, Supabase has everything
```

2024-07-09 01:55 UTC, tianzhou approved these changes
LGTM

2024-07-09 01:57 UTC, merged