docs: publish blog how to configure clickhouse ssl connection
bytebase/bytebase.com pull request #358
Opened 2022-07-20 03:34 UTC by h3n4l

2022-07-20 05:56 UTC, boojack requested changes
Some nits about format

2022-07-20 05:56 UTC, boojack commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +Follow the [OpenSSL’s official site](https://www.openssl.org/source/). Depending on the machine environment, there may be different ways to achieve this.
```suggestion
Follow the [OpenSSL's official site](https://www.openssl.org/source/). Depending on the machine environment, there may be different ways to achieve this.
```

2022-07-20 05:56 UTC, boojack commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +To generate Root CA certificate and other peers' certificate request, you need to set up a configure file as below:
```suggestion
To generate Root CA certificate and other peer's certificate request, you need to set up a configure file as below:
```

2022-07-20 06:37 UTC, tianzhou requested changes

2022-07-20 06:37 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +If no errors occur, you will see something like below:
no need to start on a new line

2022-07-20 06:37 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +If no errors occur, you will see something like below:
no need to start on a new line

2022-07-20 06:37 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +Use the server key and OpenSSL config above to generate the certificate of server like what you have done for CA. But the difference is that at this time you need to request the CA's Key for signing.
```suggestion
Use the server key and OpenSSL config above to generate the server certificate like what you have done for CA. But the difference is that at this time you need to request the CA's Key for signing.
```

2022-07-20 06:37 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +From the SSL authentication perspective, Client an Server are equal partners, so you use the same steps as the server to generate client-related SSL files.
```suggestion
From the SSL authentication perspective, Client and Server are equal partners, so you use the same steps as the server to generate client-related SSL files.
```

2022-07-20 06:37 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +**Replace YOUR_PASSWORD with the real password of the default user of ClickHouse and replace YOUR_CLICKHOUSE_SERVER_IP with the real IP of the machine that runs ClickHouse server.**
```suggestion
**Replace YOUR_PASSWORD with the real default user password of your ClickHouse server and replace YOUR_CLICKHOUSE_SERVER_IP with the real IP of the machine that runs the ClickHouse server.**
```

2022-07-20 06:37 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +Use MySQL client to connect the ClickHouse server via SSL.Run the following command, and you are expected to get some output like below:
```suggestion
Use MySQL client to connect the ClickHouse server via SSL. Run the following command, and you are expected to get some output like below:
```

2022-07-21 02:19 UTC, h3n4l commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +If no errors occur, you will see something like below:
Done.

2022-07-21 06:23 UTC, tianzhou submitted a review, later dismissed
Some nit

2022-07-21 06:23 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +author: zp
Need to use Zipeng otherwise, the avatar won't show up

2022-07-21 06:23 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +2. Generate SSL Realated Files
```suggestion
2. Generate SSL Related Files
```

2022-07-21 06:23 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +Uncommenting the listen_host tag:
```suggestion
Uncommenting the `listen_host` tag:
```

2022-07-21 06:23 UTC, tianzhou commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +You don't need to do anything in this step if you only test it on the machine that Clickhouse server runs on. Copy the ca.pem,client.pem,client.key from the machine that runs ClickHouse server (i.e.:
```suggestion
You don't need to do anything in this step if you only test it on the machine that Clickhouse server runs on. Copy the `ca.pem`, `client.pem`, `client.key` from the machine that runs ClickHouse server (i.e.: the machine generated them) to directory `/etc/ssl` on the machine that you will run the client.
```

2022-07-21 07:24 UTC, h3n4l commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +author: zp
Done.

2022-07-21 08:00 UTC, h3n4l commented
PTAL. @tianzhou

2022-07-21 08:03 UTC, tianzhou approved these changes
LGTM

2022-07-21 15:16 UTC, boojack submitted a review, later dismissed
LGTM

2022-07-21 15:32 UTC, d-bytebase commented on content/blog/how-to-configure-clickhouse-ssl-connection.md
> +2. Generate SSL related file.
```suggestion
2. Generate SSL related file
```

2022-07-22 00:30 UTC, d-bytebase approved these changes

2022-07-22 00:30 UTC, merged