docs: deploy to kubernetes
bytebase/bytebase.com pull request #366
Opened 2022-07-22 09:09 UTC by boojack

2022-07-22 15:32 UTC, tianzhou requested changes

2022-07-22 15:32 UTC, tianzhou commented on content/docs/en/get-started/install/deploy-to-kubernetes.md
> +3. Open a browser and visit [localhost:30001](http://localhost:30001), you should see Bytebase.
Normally the port should match https://www.bytebase.com/docs/administration/production-setup#make-sure---host---port-match-exactly-to-the-hostport-address-where-bytebase-supposed-to-be-visited

What's the specific reason of using 30001 instead of 8080

2022-07-22 15:32 UTC, tianzhou commented on content/docs/en/get-started/install/deploy-to-kubernetes.md
> +## More configuration in production
No need to mention this and we can lift Persistent Volume as h2

2022-07-22 15:32 UTC, tianzhou commented on content/docs/en/get-started/install/deploy-to-kubernetes.md
> +
We can have h3 section for different cloud providers

2022-07-22 15:32 UTC, tianzhou commented on content/docs/en/_layout.md
> +#### [Option 4 Deploy to Kubernetes](/get-started/install/deploy-to-kubernetes)
Put this as Option 2

2022-07-22 15:48 UTC, boojack commented on content/docs/en/get-started/install/deploy-to-kubernetes.md
> +3. Open a browser and visit [localhost:30001](http://localhost:30001), you should see Bytebase.
> By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767) https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport

It looks like the `nodeport` service in Kubernetes only supports a range from 30000-32767.

2022-07-23 02:20 UTC, boojack commented on content/docs/en/get-started/install/deploy-to-kubernetes.md
> +3. Open a browser and visit [localhost:30001](http://localhost:30001), you should see Bytebase.
Updated with `LoadBalancer` instead of `NodePort`.

2022-07-23 02:21 UTC, boojack commented
PTAL

2022-07-23 02:34 UTC, d-bytebase approved these changes

2022-07-23 03:04 UTC, tianzhou approved these changes
LGTM

2022-07-23 03:05 UTC, merged