The feature release blog for gh-ost(beta)
Bytebase/bytebase.com pull request #412
Opened 2022-08-09 02:48 UTC by candy2255

2022-08-09 06:26 UTC, tianzhou requested changes
Also please change the filename

2022-08-09 07:50 UTC, candy2255 commented on content/blog/Introducing-gh-ost-based-online-schema-migration-for-mysql
> +feature_image: /static/blog/Introducing-gh-ost-based-online-schema-migration-for-mysql/cover.webp
OK

2022-08-09 08:57 UTC, tianzhou requested changes

2022-08-09 08:57 UTC, tianzhou commented on content/blog/gh-ost-based-online-schema-migration-for-mysql.md
> +title: “gh-ost Based Online Schema Migration for MySQL”
```suggestion
title: gh-ost Based Online Schema Migration for MySQL
```

2022-08-09 08:57 UTC, tianzhou commented on content/blog/gh-ost-based-online-schema-migration-for-mysql.md
> +All existing online schema change solutions share a similar workflow:
nice illustration

2022-08-09 08:57 UTC, tianzhou commented on content/blog/gh-ost-based-online-schema-migration-for-mysql.md
> +2. Select **Online migration**and click **Next.**
```suggestion
2. Select **Online migration** and click **Next.**
```

2022-08-09 08:57 UTC, tianzhou commented on content/blog/gh-ost-based-online-schema-migration-for-mysql.md
> +![step_3](/static/blog/gh-ost-based-online-schema-migration-for-mysql/step_3.webp)
image is missing

2022-08-10 01:44 UTC, tianzhou submitted a review, later dismissed
LGTM. Nice work

2022-08-10 04:33 UTC, tianzhou approved these changes
LGTM

2022-08-10 12:16 UTC, merged