docs: add alibaba-cloud-computenest deploy doc
bytebase/bytebase.com pull request #429
Opened 2024-10-09 11:39 UTC by KunSir991

2024-10-09 13:02 UTC, tianzhou requested changes
Thanks for the contribution. Could you please remove the pnpm-lock and sql-review change?

You many need to pull the latest commit.

2024-10-10 02:03 UTC, KunSir991 commented
> Thanks for the contribution. Could you please remove the pnpm-lock and sql-review change?
> 
> You many need to pull the latest commit.
我已经按照要求修改好，再给继续review下

2024-10-10 02:07 UTC, tianzhou requested changes
Please remove the pnpm-lock file

2024-10-10 02:34 UTC, KunSir991 commented on pnpm-lock.yaml
> +    dev: false
这里不明白为何会这样。

2024-10-10 03:02 UTC, KunSir991 commented
![image](https://github.com/user-attachments/assets/eb478089-6039-486b-9127-c628375cb246)
这里没有任何实质的改动 仅是显示的问题

2024-10-10 03:20 UTC, tianzhou approved these changes
LGTM. Thanks.

2024-10-10 03:20 UTC, merged

2024-10-10 03:29 UTC, KunSir991 commented
How long will it take for the merge to take effect on the official website?