docs: blog for the best practices of goreleaser and cgo
bytebase/bytebase.com pull request #441
Opened 2022-08-24 07:18 UTC by rebelice

2022-08-24 09:25 UTC, tianzhou requested changes
the image needs to use - instead of underscore(_) as the word separator

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +If the cross-compilation toolchain is well maintained, the risk is relatively small. The main problem is when the target platform is Darwin. Anyone who has tried to cross-compile from Linux to Darwin
`The o64-clang/oa64-clang cross-compilation toolchain used by the GoReleaser-cross is built based on the [osxcross](https://github.com/tpoechtrager/osxcross)`

Not sure what's our intention here, do we suggest that osxcross is a well-maintained one (there is 2.2k star) . But if it's a well-maintained one, then this seems to be a counter-example, because we just mentioned the difficulty of finding a well-maintained toolchain.

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +For the Darwin platform GoReleaser configuration file, we just need to open CGO.
```suggestion
For the Darwin platform GoReleaser configuration file, we just need to enable CGO.
```

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +Up to this point, we can use GoReleaser to compile when CGO is on, but the story is not over yet. The ultimate goal of GoReleaser is to release, and if we use GoReleaser twice as we currently do, we
```suggestion
Up to this point, we can use GoReleaser to compile when CGO is on, but the story is not over yet. The ultimate goal of GoReleaser is to release, and if we use GoReleaser twice as we currently do, we will generate two releases. But compared to the cross-compilation headache, this is a piece of cake.
```

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +The main idea here is simple: separate the building and the release.
```suggestion
The main idea here is simple: separate the building process from the release.
```

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +- Job three depends on job one and job two. Then it does the final release.
```suggestion
- Job one builds all Linux binaries.
- Job two builds all macOS binaries.
- Job three packages the binaries from job one and two into the final release.
```

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +Job one and two skip the release with the skip-publish argument. Job three skips the building and uses the files generated in jobs one and two with the extra_files setting.
```suggestion
Job one and two skip the release with the skip-publish argument. Job three skips the building stage and uses the files generated in jobs one and two with the extra_files setting.
```

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +The thing is CGO was not opened in GoReleaser. And go-sqlite3 did a [mock](https://github.com/mattn/go-sqlite3/blob/master/static_mock.go) when CGO was not opened, which means that the go-sqlite3 com
```suggestion
The thing is CGO was not enabled in GoReleaser. And go-sqlite3 did a [mock](https://github.com/mattn/go-sqlite3/blob/master/static_mock.go) when CGO was not enabled, which means that the go-sqlite3 compiled without CGO was an empty package.
```

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +- Don't try to introduce a cross-compilation toolchain unless you absolutely have to. It will incur additional verification and maintenance costs.
I think it worth mentioning GitHub action simplifies a lot because it provides all arch for a platform

2022-08-24 09:25 UTC, tianzhou commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +title: How We Explored the Best Practices of GoReleaser X CGO
Title: How to cross compile with CGO using GoReleaser and GitHub Action

filename: how-to-cross-compile-with-cgo-use-goreleaser-and-github-action.md


For SEO

2022-08-24 09:34 UTC, rebelice commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +If the cross-compilation toolchain is well maintained, the risk is relatively small. The main problem is when the target platform is Darwin. Anyone who has tried to cross-compile from Linux to Darwin
Got it. I'll remove it.

2022-08-24 09:48 UTC, rebelice commented on content/blog/how-we-explored-the-best-practices-of-goreleaser-x-cgo.md
> +In the [1.2.1 release](https://github.com/Bytebase/Bytebase/tree/release/1.2.1), we found that the [GoReleaser](https://github.com/goreleaser/goreleaser) did not work correctly, and the error message
Do you mean chanelog/bytebase-1-2-1?

2022-08-24 09:54 UTC, rebelice commented
Updated. PTAL @tianzhou

2022-08-24 10:05 UTC, tianzhou approved these changes
LGTM. Nice write-up and cool cover image.

2022-08-25 02:37 UTC, adela-bytebase approved these changes
LGTM

2022-08-25 02:38 UTC, merged