chore: initial the app docs
bytebase/bytebase.com pull request #507
Opened 2022-09-15 10:17 UTC by ecmadao

Init the docs for the GitHub App. We need to add more details and screenshots using the app in the release env

2022-09-15 10:58 UTC, tianzhou approved these changes
LGTM

2022-09-15 10:58 UTC, tianzhou commented on content/docs/en/sql-review/sql-advisor/github-app.md
> +Bytebase also provides the [GitHub App](https://github.com/marketplace/bytebase) to let users integrate the SQL review into their GitHub CI.
```suggestion
Bytebase also provides the [GitHub App](https://github.com/marketplace/bytebase) to let users integrate the SQL review into their GitHub PR workflow.
```

2022-09-15 10:58 UTC, tianzhou commented on content/docs/en/sql-review/sql-advisor/overview.md
> +- [**GitHub Action**](/docs/sql-review/sql-advisor/github-action) - If all your sql files are stored on GitHub.com, you can use GitHub action to do prechecks before they're merged into the main branc
```suggestion
- [**GitHub Action**](/docs/sql-review/sql-advisor/github-action) - If all your SQL files are stored on GitHub.com, you can use GitHub action to do prechecks before they're merged into the main branch.
```

2022-09-15 10:58 UTC, tianzhou commented on content/docs/en/sql-review/sql-advisor/overview.md
> +- [**GitHub App**](/docs/sql-review/sql-advisor/github-app) - If all your sql files are stored on GitHub.com, you can use GitHub app to do prechecks before they're merged into the main branch. No cod
```suggestion
- [**GitHub App**](/docs/sql-review/sql-advisor/github-app) - If all your SQL files are stored on GitHub.com, you can use GitHub app to do prechecks before they're merged into the main branch. No coding is required, deploy your SQL check in minutes.
```

2022-09-16 02:55 UTC, ecmadao commented
I updated the docs and add the screenshots. PTAL @tianzhou

2022-09-16 03:19 UTC, tianzhou requested changes

2022-09-16 03:19 UTC, tianzhou commented on content/docs/en/sql-review/sql-advisor/github-app.md
> +- **Database dialect**: the database dialect for your repository. For now we support MySQL (including TiDB) and PostgreSQL (including CockroachDB)
Let's use list e.g.

For now, we support:
* MySQL dialect, vanilla MySQL, and other database engines adopting its dialect such as TiDB.
* PostgreSQL dialect, vanilla PostgreSQL, and other database engines adopting its dialect such as CockroachDB.

2022-09-16 03:19 UTC, tianzhou commented on content/docs/en/sql-review/sql-advisor/github-app.md
> +You can customize the rule level and payload in step 2. You can [follow this doc](/docs/sql-review/review-rules/create-schema-review-policy#step-2) for details about rule configuration.
```suggestion
You can customize the rule level and payload in step 2. You can [follow this doc](/docs/sql-review/review-rules/create-schema-review-policy#step-2) for details about the rule configuration.
```

2022-09-16 04:30 UTC, ecmadao commented on content/docs/en/sql-review/sql-advisor/github-app.md
> +- **Database dialect**: the database dialect for your repository. For now we support MySQL (including TiDB) and PostgreSQL (including CockroachDB)
Updated
<img width="965" alt="图片" src="https://user-images.githubusercontent.com/10706318/190557012-67e11ce3-ba2d-4e79-a2b6-474f93da8585.png">

2022-09-16 04:50 UTC, tianzhou approved these changes
LGTM

2022-09-16 04:50 UTC, merged