add-clickhouse-blog
bytebase/bytebase.com pull request #519
Opened 2022-09-25 10:28 UTC by adela-bytebase

2022-09-25 13:03 UTC, milasuperstar commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +We spend another couple of months to make our infrastructure ready (It’s not just for Bytebase, but for our overall platform readiness to onboard new services). About three months ago, when everythin
```suggestion
We spent another couple of months to make our infrastructure ready (It’s not just for Bytebase, but for our overall platform readiness to onboard new services). About three months ago, when everything was ready, we started to deploy Bytebase to our production environment. Since we had tested extensively in our Dev environment, we thought the process would be smooth.
```

2022-09-26 04:35 UTC, tianzhou requested changes

2022-09-26 04:35 UTC, tianzhou commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +title: How does a ClickHouse Data Team Use Bytebase for Managing Schema Change
How a Data Team Uses Bytebase to Manage Schema Change for ClickHouse

2022-09-26 04:35 UTC, tianzhou commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +We have roughly three problems:
```suggestion
We have three main problems:
```

2022-09-26 04:35 UTC, tianzhou commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +We’re a data team within a 500-person company. The company has several customer-facing products, and we are a group of data scientists analyzing data to uncover customer, product, and operational ins
```suggestion
We’re a data team within a 500-person company. The company has several customer-facing products, and we are a group of data scientists analyzing data to uncover customer, product, and operational insights:
```

2022-09-26 04:35 UTC, tianzhou commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +# Context
We need to start with ## (h2) in the blog, otherwise the TOC looks bad

<img width="1237" alt="CleanShot 2022-09-26 at 12 31 36@2x" src="https://user-images.githubusercontent.com/230323/192194331-8df6d369-3fa4-4d60-8099-3ec5c72e2c50.png">

2022-09-26 04:35 UTC, tianzhou commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +The practice in detail is now in Bytebase’s recommended workflow: https://www.bytebase.com/docs/how-to/workflow/gitops-feature-branch
Use relative URL

2022-09-26 04:35 UTC, tianzhou commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +- Also, a nice UI to oversee the process.
Forget to mention the schema write-back, that customer did mention their downstream pipeline observed that latest schema file

2022-09-30 07:09 UTC, adela-bytebase commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +- Also, a nice UI to oversee the process.
- How the migration happens - there are activities recording every state change and writing back to the "latest schema" file?

2022-10-09 09:22 UTC, tianzhou approved these changes
LGTM

2022-10-09 09:22 UTC, tianzhou commented on content/blog/how-a-clickhouse-data-team-uses-bytebase-for-managing-schema-change.md
> +    - How the migration happens - there are activities recording every state change and writing back to the lastest schema file.
```suggestion
    - When the migration happens - the start time, finish time.
    - Why the migration happens - in our GitOps setup, Bytebase links back to the commit page from GitLab.
    - What’s the exact migration - the migration script and the before/after full schema snapshot.
    - How the migration happens - there are activities recording every state change.
```

2022-10-09 09:22 UTC, tianzhou commented on content/blog/how-a-clickhouse-data-team-uses-bytebase-for-managing-schema-change.md
> +- Also, a nice UI to oversee the process.
```suggestion
- Schema write-back - after the migration completes, Bytebase will write the entire latest schema back to the specified location in the Git repository. We use this feature to configure our downstream data pipeline to observe that schema file. 
- Also, a nice UI to oversee the process.
```

2022-10-09 09:23 UTC, tianzhou commented on content/blog/how-does-a-clickhouse-data-team-use-bytebase-for-managing-schema-change.md
> +- Also, a nice UI to oversee the process.
I made the edit. PTAL

2022-10-09 09:37 UTC, merged