feat: add docs for backup to the cloud
bytebase/bytebase.com pull request #522
Opened 2022-09-27 07:53 UTC by dragonly

2022-09-27 12:21 UTC, tianzhou requested changes

2022-09-27 12:21 UTC, tianzhou commented on content/docs/en/disaster-recovery/backup-restore-database/cloud-backup.md
> +  bytebase/bytebase:1.4.0 \
use %%bb_version%%

2022-09-27 12:21 UTC, tianzhou commented on content/docs/en/disaster-recovery/backup-restore-database/cloud-backup.md
> +Caveat: If you used to run Bytebase without these flags, you might already have backups in your local disk. They can be successfully restored even if you run Bytebase with the new flags to store new
```suggestion
Caveat: If you used to run Bytebase without these flags, you might already have backups in your local disk. They can be successfully restored even if you run Bytebase with the new flags to store new backups in the AWS S3. But we still recommend that you do at least one backup for the production databases after Bytebase switches to the cloud backup. This ensures that there are backups in the cloud storage and that your data is safe.
```

2022-09-27 12:35 UTC, dragonly commented on content/docs/en/disaster-recovery/backup-restore-database/cloud-backup.md
> +  bytebase/bytebase:1.4.0 \
Fixed.

2022-09-27 12:54 UTC, tianzhou approved these changes
LGTM

2022-09-28 01:37 UTC, milasuperstar reviewed
rest LGTM

2022-09-28 01:37 UTC, milasuperstar commented on content/docs/en/disaster-recovery/backup-restore-database/cloud-backup.md
> +Please substitute the `<YOUR-BUCKET-NAME-HERE>` part with your actual bucket name. Do not change the Version field’s value, which is the newest version of the AWS policy language.
```suggestion
Please substitute the `<YOUR-BUCKET-NAME-HERE>` part with your actual bucket name. Do not change the "Version" field’s value, which is the newest version of the AWS policy language.
```

2022-09-28 03:33 UTC, merged