docs: add sql review rules
bytebase/bytebase.com pull request #557
Opened 2022-10-26 08:10 UTC by rebelice

This PR only adds the text part. 
Pictures will be added in the next PR.

2022-10-26 14:17 UTC, tianzhou requested changes
Good progress.

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +- `CREATE TABLE` statements
Why not ALTER TABLE?

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +Bytebase checks if SQLs use the column type in disallow list.
```suggestion
Bytebase checks if the SQL statement creates the column type in the disallow list.
```

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +Changing column type may fail because the data cannot be converted. Bytebase provides this rule to alert you that a type changing has occurred.
```suggestion
Changing column type may fail because the data cannot be converted. Bytebase provides this rule to alert you that the SQL statement would change the column type.
```

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +Bytebase checks if SQLs change the column type.
```suggestion
Bytebase checks if the SQL statement will change the column type.
```

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +Most of the time, you just want to change the one of two. So you need to use RENAME COLUMN and MODIFY COLUMN instead of CHANGE COLUMN to avoid unexpected modifications.
```suggestion
CHANGE COLUMN is a MySQL extension to standard SQL. CHANGE COLUMN can change column definition and names, or both.
Most of the time, you just want to change one of two. So you need to use RENAME COLUMN and MODIFY COLUMN instead of CHANGE COLUMN to avoid unexpected modifications.
```

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +The auto-increment column must integer in MySQL.
```suggestion
The auto-increment column must be integer.
```

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +The VARCHAR type is the variable-length type but the CHAR is not. When users need a long CHAR type, it's better to use VARCHAR instead of CHAR.
This reasoning is a bit unrelated. We should explain why we need to enforce CHAR length instead of why VARCHAR is better than CHAR

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +Alert users if key type is not ING or BIGINT in primary keys.
```suggestion
Alert users if key type is not INT or BIGINT in primary keys.
```

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +Bytebase checks if SQLs use the charset not in allow list.
```suggestion
Bytebase checks if the SQL statement uses the charset outside of the allow list.
```

2022-10-26 14:17 UTC, tianzhou commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +Bytebase checks if SQLs use the collation not in allow list.
```suggestion
Bytebase checks if the SQL statement uses the collation outside of the allow list.
```

2022-10-26 14:33 UTC, d-bytebase commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +`Auto-increment Column Naming Convention` uses [regular expression](https://en.wikipedia.org/wiki/Regular_expression) format for naming pattern, and also limits the naming max length. The default max
nit: s/max/maximum

Always use full English words in articles, consistently at least.

2022-10-26 14:33 UTC, d-bytebase commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +Bytebase checks that all auto-increment column names in DDL conform to the naming conventions.
```suggestion
Bytebase checks all auto-increment column names in DDL conforming to the naming conventions.
```

2022-10-27 02:45 UTC, rebelice commented on content/docs/en/sql-review/review-rules/supported-rules.md
> +- `CREATE TABLE` statements
Consider the following case:
```
CREATE TABLE table_t(...);
ALTER TABLE table_t ...;
ALTER TABLE table_t ...;
```
We need to merge them as one `CREATE TABLE` statements

2022-10-27 02:59 UTC, rebelice commented
Fixed all. PTAL @tianzhou @d-bytebase

2022-10-27 07:18 UTC, tianzhou approved these changes
LGTM

2022-10-27 07:24 UTC, merged