docs: sync schema
bytebase/bytebase.com pull request #613
Opened 2022-11-11 09:03 UTC by boojack

2022-11-11 15:25 UTC, tianzhou requested changes

2022-11-11 15:25 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +Synchronize schema can identify the inconsistent database schema and get the DDL statements through the structure comparison function. The user can synchronize one database schema to another database
```suggestion
Bytebase can synchronize one database schema to another database. To synchronize the schema, Bytebase calculates the schema diff between the two databases and generates the required DDL statements (e.g. ALTER TABLE).
```

2022-11-11 15:25 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +2. Select schema
```suggestion
2. Select schema version
```

2022-11-11 15:25 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +   The schema should be one of the database's migration history. The default is the latest.
```suggestion
   The schema version is selected from the database's migration history.
```

2022-11-11 15:25 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +   In the Enterprise Plan, you can set a special schema version from migration history list.
```suggestion
   In the Enterprise Plan, you can select an arbitrary schema version from the migration history. In other plans, you can only select the latest schema version.
```

2022-11-11 15:25 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +   Select the database that will be synchronized with the previously selected schema.
```suggestion
   Select the database that will be synchronized with the chosen schema version in the last step.
```

2022-11-11 15:25 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +4. The generated DDL statement
```suggestion
4. Generated DDL statements
```

2022-11-11 15:25 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +   Bytebase will show a code diff between two database schema and generate the DDL statement. You can further edit the generated DDL statement.
```suggestion
   Bytebase will show a schema diff between two databases and generate the DDL statements. You can further edit the generated content.
```

2022-11-11 15:25 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +   With the generated DDL statement, you can preview and create an "Alter Schema" issue for the selected database.
```suggestion
   With the generated DDL statements, you can preview and create an "Alter Schema" issue. This kicks off the [change workflow](/docs/change-database/change-workflow) for the applied database.
```

2022-11-14 08:10 UTC, candy2255 commented on content/docs/change-database/synchronize-schema.md
> +
It would be great to tell users how to launch the dialog below.

2022-11-14 08:14 UTC, candy2255 commented on content/docs/change-database/synchronize-schema.md
> +1. Select project
We recommend replacing "1." with "Step 1 -".
![CleanShot 2022-11-14 at 16 11 02@2x](https://user-images.githubusercontent.com/104962472/201608238-c34baa55-4194-4c57-9dd7-f4ccfe63be54.png)

2022-11-14 08:28 UTC, candy2255 commented on content/docs/change-database/synchronize-schema.md
> +4. Generated DDL statements
I think "Generated DDL statements" is a result of Step 3. So I suggest merging Step 4 into Step 3.

2022-11-14 08:52 UTC, candy2255 requested changes

2022-11-14 08:52 UTC, candy2255 commented on content/docs/change-database/synchronize-schema.md
> +Bytebase can synchronize one database schema to another database. To synchronize the schema, Bytebase calculates the schema diff between the two databases and generates the required DDL statements (e
```suggestion
Bytebase supports synchronizing a specified schema version of one database to another. To provide a better user experience, Bytebase displays the schema differences between the two selected databases and generates the suggested DDL statements (e.g. ALTER TABLE).
```

2022-11-14 15:11 UTC, boojack commented
@candy2255 PTAL

2022-11-17 08:54 UTC, boojack commented
PTAL

2022-11-17 08:57 UTC, tianzhou approved these changes
LGTM

2022-11-17 08:57 UTC, tianzhou commented on content/docs/change-database/synchronize-schema.md
> +After you have selected a schema and database, Bytebase will show a schema diff between two databases and generate the DDL statements. And you can further edit the generated content.
```suggestion
After you have selected a schema and database, Bytebase will show a schema diff between the two databases and generate the DDL statements. And you can further edit the generated content.
```

2022-11-17 09:22 UTC, candy2255 approved these changes
LGTM

2022-11-17 09:23 UTC, merged