docs: add docs about deployment to Kubernetes with helm
bytebase/bytebase.com pull request #616
Opened 2022-11-13 03:23 UTC by h3n4l

2022-11-13 04:32 UTC, tianzhou requested changes

2022-11-13 04:32 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-kubernetes.md
> +--set "bytebase.option.external-url"="https://bytebase.com" \
```suggestion
--set "bytebase.option.external-url"="https://bytebase.example.com" \
```

2022-11-13 04:32 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-kubernetes.md
> +--set "bytebase.option.pg"="postgresql://bytebase:bytebase@database.bytebase.ap-east-1.rds.amazonaws.com/bytebase" \
```suggestion
--set "bytebase.option.pg"="postgresql://user:secret@foo.ap-east-1.rds.amazonaws.com/postgres" \
```

2022-11-13 04:32 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-kubernetes.md
> +<hint-block type="info">
This can be put at the start of the section "Deploy to Kubernetes with Helm"

And use the exact wording as /docs/get-started/install/deploy-with-docker#run-on-httpsbytebaseexamplecom

2022-11-14 02:21 UTC, h3n4l commented on content/docs/get-started/install/deploy-to-kubernetes.md
> +<hint-block type="info">
Done.

2022-11-14 02:22 UTC, h3n4l commented
PTAL @tianzhou

2022-11-14 04:24 UTC, tianzhou approved these changes
LGTM

2022-11-14 04:24 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-kubernetes.md
> +###
Not sure if we need this

2022-11-14 05:31 UTC, h3n4l commented on content/docs/get-started/install/deploy-to-kubernetes.md
> +###
It's a wrong commit : /, I add the title of this hint block. PTAL @tianzhou

2022-11-14 06:41 UTC, merged