docs: deploy bytebase via rainbond
bytebase/bytebase.com pull request #622
Opened 2022-11-14 16:19 UTC by zzzhangqi

Signed-off-by: Qi Zhang <smallqi1@163.com>

2022-11-14 16:56 UTC, tianzhou requested changes

2022-11-14 16:56 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +You need to have a Rainbond. Please ref [Rainbond Quick Install](https://rainbond.com/docs/quick-start/quick-install).
```suggestion
To install Rainbond, please refer to [Rainbond Quick Install](https://rainbond.com/docs/quick-start/quick-install).
```

2022-11-14 16:56 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +After login in to Rainbond, click `Market` in the left menu, switch to open source app store, and search `Bytebase` in the search box, and click Install button.
```suggestion
After logging in Rainbond, click `Market` in the left menu, switch to open source app store, and search `Bytebase` in the search box, and click the Install button.
```

2022-11-14 16:56 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +![](/static/docs/get-started/install/rainbond-install.png)
Images need to be converted to webp format

2022-11-14 16:56 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +Fill in the installation information, and click Confirm button startup install.
```suggestion
Fill in the following information, and click `Confirm` button to install.
```

2022-11-14 16:56 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +Moment later, Bytebase will be installed successfully, via the Access button to access Bytebase.
```suggestion
After installation, Bytebase can be accessed via the `Access` button.
```

2022-11-14 16:56 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +> Via Rainbond installed Bytebase, external PostgreSQL is used by default.
Let's used the hint block https://bytebase.com/docs/document-write-guide#hint

2022-11-15 02:33 UTC, zzzhangqi commented
@tianzhou All suggestion have been submitted. but cla failed to pass, I have signed cla.

2022-11-15 14:40 UTC, tianzhou commented
> @tianzhou All suggestion have been submitted. but cla failed to pass, I have signed cla.

@zzzhangqi you need to add your name to https://github.com/bytebase/clabot-config/blob/main/.clabot

2022-11-15 14:52 UTC, tianzhou requested changes

2022-11-15 14:52 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +If you don't have Container and Kubernetes knowledge, And want to install Bytebase in Kubernetes, you can use Rainbond to deploy bytebase. [Rainbond](http://www.rainbond.com) is cloud native applicat
```suggestion

If you are unfamiliar with Kubernetes, and want to install Bytebase in Kubernetes, you can use Rainbond to deploy. [Rainbond](http://www.rainbond.com) is a cloud-native application management platform built on Kubernetes and simplifies the application deployment to Kubernetes.
```

2022-11-15 14:52 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +External URL for Bytebase is provided by Rainbond by default, You can go to the Bytebase component -> Environment configuration, Modify `EXTERNAL_URL` Environment Variables to customize the external
```suggestion
Rainbond uses [--external-url](/docs/get-started/install/external-url) to store the Bytebase metadata in the external PostgreSQL. You can go to the Bytebase component -> Environment configuration, Modify `EXTERNAL_URL` Environment Variables to customize the external URL.
```

2022-11-15 15:37 UTC, zzzhangqi commented on content/docs/get-started/install/deploy-to-rainbond.md
> +External URL for Bytebase is provided by Rainbond by default, You can go to the Bytebase component -> Environment configuration, Modify `EXTERNAL_URL` Environment Variables to customize the external
This is two paragraphs.

Rainbond uses [--pg](/docs/get-started/install/external-postgres) to store the Bytebase metadata in the external PostgreSQL.

Rainbond uses [--external-url](/docs/get-started/install/external-url) to provides external access to Bytebase. You can go to the Bytebase component -> Environment configuration, Modify `EXTERNAL_URL` Environment Variables to customize the external URL.

2022-11-15 15:40 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +External URL for Bytebase is provided by Rainbond by default, You can go to the Bytebase component -> Environment configuration, Modify `EXTERNAL_URL` Environment Variables to customize the external
My bad. Got drunk

2022-11-15 15:45 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +External URL for Bytebase is provided by Rainbond by default, You can go to the Bytebase component -> Environment configuration, Modify `EXTERNAL_URL` Environment Variables to customize the external
```suggestion
Rainbond uses [--pg](/docs/get-started/install/external-postgres) to store the Bytebase metadata in the external PostgreSQL.

Rainbond uses [--external-url](/docs/get-started/install/external-url) to provide external access to Bytebase. You can go to the Bytebase component -> Environment configuration, and Modify EXTERNAL_URL Environment Variables to customize the external URL.
```

2022-11-15 15:45 UTC, tianzhou commented on content/docs/get-started/install/deploy-to-rainbond.md
> +External URL for Bytebase is provided by Rainbond by default, You can go to the Bytebase component -> Environment configuration, Modify `EXTERNAL_URL` Environment Variables to customize the external
@zzzhangqi please see the new edit, but I have a question, do we provide the similar ENV variable for configuring external PG?

2022-11-15 15:49 UTC, zzzhangqi commented on content/docs/get-started/install/deploy-to-rainbond.md
> +External URL for Bytebase is provided by Rainbond by default, You can go to the Bytebase component -> Environment configuration, Modify `EXTERNAL_URL` Environment Variables to customize the external
Yes, provide. `POSTGRES_HOST` `POSTGRES_PORT` `POSTGRES_DB` `POSTGRES_USER` `POSTGRES_PASSWORD`

2022-11-15 16:01 UTC, tianzhou reviewed
Please take a look at the suggested edit

2022-11-15 16:11 UTC, zzzhangqi commented
@tianzhou All suggestion have been submitted.

2022-11-15 16:43 UTC, tianzhou requested changes

2022-11-15 16:43 UTC, tianzhou commented on content/docs/_layout.md
> +#### [Option 6 Deploy to Rainbond](/get-started/install/deploy-to-rainbond)
let's make this option 4

2022-11-16 02:12 UTC, zzzhangqi commented
@tianzhou All suggestion have been submitted.

2022-11-16 09:24 UTC, merged

2022-11-16 09:25 UTC, tianzhou commented
> @tianzhou All suggestion have been submitted.

Thanks for the contribution. Looking forward to the collaboration between Rainbond and Bytebase!