docs: add Tenant GitOps page
bytebase/bytebase.com pull request #631
Opened 2022-11-17 11:37 UTC by unknwon

This PR adds a new page **Tenant Database Management > Tenant GitOps**.

---

Closes https://linear.app/bytebase/issue/BYT-1759/tenant-yaml-documentation

2022-11-17 12:07 UTC, tianzhou requested changes

2022-11-17 12:07 UTC, tianzhou commented on content/docs/tenant-database-management/tenant-gitops.md
> +Using SQL files as migration scripts has the limitation of only being able to target a single database, to make a data change across an arbitrary set of databases, you can use a YAML manifest without
Remove the "without any configuration change on the UI." part?

2022-11-17 12:07 UTC, tianzhou commented on content/docs/tenant-database-management/tenant-gitops.md
> +1. The **File path template** must use `.sql` as the file extension for migration scripts.
yml?

And do we support .yaml?

2022-11-17 12:07 UTC, tianzhou commented on content/docs/tenant-database-management/tenant-gitops.md
> +Please be noted that the database name in the file path ("store") is now completely ignored.
```suggestion
Please be noted if you specify the database name ("store") in the file path, it will be ignored.
```

2022-11-17 12:07 UTC, tianzhou commented on content/docs/tenant-database-management/tenant-gitops.md
> +Both SQL files and YAML manifests can co-exist and be used on per-migration basis depending on your needs. Your VCS repository for storing migartion scripts could look like follows after several migr
```suggestion
Both SQL files and YAML manifests can co-exist and be used on per-migration basis depending on your needs. After several migrations, your VCS repository for storing migration scripts could look like follows:
```

2022-11-17 12:07 UTC, tianzhou commented on content/docs/tenant-database-management/tenant-gitops.md
> ++bytebase/Staging/store##0003##dml##insert-companies.yml
any specific reason to use "Staging" instead of "staging"?

normally we use lower case

2022-11-17 12:35 UTC, unknwon commented on content/docs/tenant-database-management/tenant-gitops.md
> +Using SQL files as migration scripts has the limitation of only being able to target a single database, to make a data change across an arbitrary set of databases, you can use a YAML manifest without
Why? 🤔

2022-11-17 12:36 UTC, unknwon commented on content/docs/tenant-database-management/tenant-gitops.md
> +1. The **File path template** must use `.sql` as the file extension for migration scripts.
We don't support `.yaml`, and this sentence is correct with `.sql`, because we replace `.sql` with `.yml` for the file path template at matching time behind the sense if the committed file is ending with `.yml`.

2022-11-17 12:37 UTC, tianzhou commented on content/docs/tenant-database-management/tenant-gitops.md
> +Using SQL files as migration scripts has the limitation of only being able to target a single database, to make a data change across an arbitrary set of databases, you can use a YAML manifest without
what's the important info that "without any configuration change on the UI" tries to convey otherwise reader could miss?

2022-11-17 12:40 UTC, unknwon commented on content/docs/tenant-database-management/tenant-gitops.md
> +Please be noted that the database name in the file path ("store") is now completely ignored.
I don't think this is a "if" situation, because once the `{{DB_NAME}}` placeholder is used in the file path template, it is required (and the "if" would give the ambiguity/false-assumption to the user that they can actually omit the database name).

2022-11-17 12:42 UTC, unknwon commented on content/docs/tenant-database-management/tenant-gitops.md
> ++bytebase/Staging/store##0003##dml##insert-companies.yml
The environment name is case-sensitive in the file path and we generate default environments like `Dev`, `Staging`, `Prod` in our product. 

<img width="727" alt="CleanShot 2022-11-17 at 20 41 20@2x" src="https://user-images.githubusercontent.com/2946214/202449249-d620350a-034e-415d-bc32-7e45afcf131f.png">

2022-11-17 12:44 UTC, unknwon commented on content/docs/tenant-database-management/tenant-gitops.md
> +Using SQL files as migration scripts has the limitation of only being able to target a single database, to make a data change across an arbitrary set of databases, you can use a YAML manifest without
I think "nothing additional is required to be able to use the YAML manifest".

2022-11-28 06:39 UTC, adela-bytebase commented on content/docs/tenant-database-management/tenant-gitops.md
> +For example, to add a new table in the "Staging" envrionment for the database "store" using the default **File path template** (`{{ENV_NAME}}/{{DB_NAME}}##{{VERSION}}##{{TYPE}}##{{DESCRIPTION}}.sql`)
"Staging" -> Staging
"store" -> store

2022-11-28 06:51 UTC, adela-bytebase commented on content/docs/tenant-database-management/tenant-gitops.md
> +Below is the file content for adding a new table for the database "supermarket":
"supermarket" -> `supermarket`

2022-11-28 06:52 UTC, adela-bytebase commented on content/docs/tenant-database-management/tenant-gitops.md
> +Please be noted that the database name in the file path ("store") is now completely ignored.
"store" -> `store`

2022-11-28 08:21 UTC, unknwon commented on content/docs/tenant-database-management/tenant-gitops.md
> +For example, to add a new table in the "Staging" envrionment for the database "store" using the default **File path template** (`{{ENV_NAME}}/{{DB_NAME}}##{{VERSION}}##{{TYPE}}##{{DESCRIPTION}}.sql`)
```suggestion
For example, to add a new table in the `Staging` envrionment for the database `store` using the default **File path template** (`{{ENV_NAME}}/{{DB_NAME}}##{{VERSION}}##{{TYPE}}##{{DESCRIPTION}}.sql`), the file path of the SQL file would look like `bytebase/Staging/store##0001##ddl##add-company-table.sql` with the following content:
```

2022-11-28 08:21 UTC, unknwon commented on content/docs/tenant-database-management/tenant-gitops.md
> +Below is the file content for adding a new table for the database "supermarket":
```suggestion
Below is the file content for adding a new table for the database `supermarket`:
```

2022-11-28 08:21 UTC, unknwon commented on content/docs/tenant-database-management/tenant-gitops.md
> +Please be noted that the database name in the file path ("store") is now completely ignored.
```suggestion
Please be noted that the database name in the file path (`store`) is now completely ignored.
```

2022-11-28 08:27 UTC, merged

2022-11-28 08:27 UTC, tianzhou commented
We can discuss remaining items later.