docs: add sql editor section
bytebase/bytebase.com pull request #64
Opened 2022-03-31 04:02 UTC by xiaoluoboding

SQL Editor order is the `30400`

2022-03-31 04:12 UTC, tianzhou commented
@xiaoluoboding @boojack not sure why the render preview is not working. Could you please take a look?

2022-03-31 04:15 UTC, boojack commented
> @xiaoluoboding @boojack not sure why the render preview is not working. Could you please take a look?

Because this branch is https://github.com/xiaoluoboding/bytebase.com.

2022-03-31 06:16 UTC, xiaoluoboding commented
> > @xiaoluoboding @boojack not sure why the render preview is not working. Could you please take a look?
> 
> Because this branch is https://github.com/xiaoluoboding/bytebase.com.

So, i don't need fork the project?

2022-03-31 07:00 UTC, boojack submitted a review, later dismissed
LGTM overall. The render's PR preview cannot works in a fork branch. https://community.render.com/t/pull-request-previews-from-branch-on-fork/1953. And I think it's ok for changing docs in main repo.

2022-03-31 07:46 UTC, tianzhou commented
> LGTM overall. The render's PR preview cannot works in a fork branch. https://community.render.com/t/pull-request-previews-from-branch-on-fork/1953. And I think it's ok for changing docs in main repo.

Yeah, I would just do it on the main repo for the doc repo for the convenience of render preview, since that's quite helpful

2022-03-31 08:18 UTC, tianzhou requested changes

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +## Run Queries
```suggestion
## Run query
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +Click the `Run` button or use the shortcut key `(⌘ + Enter)` to run your queries in SQL Editor.
```suggestion
Click the `Run` button or use the shortcut key `(⌘ + Enter)` to run your queries in the SQL Editor.
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +Use semicolons to separate multiple SQL queries. SQL Editor only runs the first query now.
```suggestion
If you have multiple SQL queries separated by semicolons, SQL Editor will only run the first query for now.
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +## Explain Queries
```suggestion
## Explain query
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +SQL Editor provides a button next to the `Run` one to run Explain queries. You can click it or use the shortcut key `(⌘ + E)` to run Explain SQL queries instead of writing them manually.
```suggestion
SQL Editor provides an `Explain` button to run EXPLAIN on the selected query. You can click it or use the shortcut key `(⌘ + E)` instead of prepending EXPLAIN manually.
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +```sql
This section seems to be redundant since we are providing the UI option to run EXPLAIN.

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +# Run/Explain Queries
```suggestion
# Run and EXPLAIN Query
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +SQL Editor provides a button next to the `Run` one to run Explain queries. You can click it or use the shortcut key `(⌘ + E)` to run Explain SQL queries instead of writing them manually.
The reason to remove "next to the `Run`" is because if we later change the UX to move the button, we won't need to update this doc.

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/run-queries.md
> +## Explain Queries
```suggestion
## EXPLAIN query
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/share-sheet-with-teammates.md
> +title: Share sheet with teammates
```suggestion
title: Share Sheet with Teammates
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/share-sheet-with-teammates.md
> +# Share sheet with teammates
```suggestion
# Share Sheet with Teammates
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/share-sheet-with-teammates.md
> +There are three types of accessibilites:
```suggestion
You can configure the sheet with one of the following access levels:
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/share-sheet-with-teammates.md
> +title: Share sheet with teammates
```suggestion
title: Share sheet
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/writing-a-query.md
> +title: Writing a Query
```suggestion
title: Compose a Query
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/writing-a-query.md
> +# Writing a Query
```suggestion
# Compose a Query
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/writing-a-query.md
> +## Autocomplete Suggestions
```suggestion
## Auto-completion
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/writing-a-query.md
> +Currently, we support the following prompts:
```suggestion
Currently, SQL Editor supports the following auto-completions:
```

2022-03-31 08:18 UTC, tianzhou commented on docs/features/sql-editor/writing-a-query.md
> +You can format SQL queries with a shortcut key `(⇧ + ⌘ + F)` to improve your codes’ readability.
```suggestion
You can click the `Format` button or use a shortcut key `(⇧ + ⌘ + F)` to format SQL queries.
```

2022-03-31 08:22 UTC, tianzhou commented
Nice try. Couple of issues spotted:

* Upper/lower case consistency. The page title, section title etc have different rules. Please be consistent with existing docs
* Plural or singular form, as with the code, for the titles, let's use singular forms if applicable. Sometimes, plural form is more appropriate, but that should be treated as an exception.
* Avoid using marketing words in the user doc. Try to be terse and direct to describe the feature.

@adela-bytebase @LucyLu8L @raytian03

2022-03-31 09:03 UTC, xiaoluoboding commented
> Nice try. Couple of issues spotted:
> 
> * Upper/lower case consistency. The page title, section title etc have different rules. Please be consistent with existing docs
> * Plural or singular form, as with the code, for the titles, let's use singular forms if applicable. Sometimes, plural form is more appropriate, but that should be treated as an exception.
> * Avoid using marketing words in the user doc. Try to be terse and direct to describe the feature.
> 
> @adela-bytebase @LucyLu8L @raytian03

The document is translated at the [Google docs](https://docs.google.com/document/d/1yzFveIxJccfTg8YLnA7GROE0j6Aw5NUJGvHzcVo7fcM/edit#heading=h.g2tv1ds4g50f), Maybe next time, we discuss on the google docs, and in here, we only need to paste the result.

2022-04-01 06:03 UTC, tianzhou commented
> > Nice try. Couple of issues spotted:
> > 
> > * Upper/lower case consistency. The page title, section title etc have different rules. Please be consistent with existing docs
> > * Plural or singular form, as with the code, for the titles, let's use singular forms if applicable. Sometimes, plural form is more appropriate, but that should be treated as an exception.
> > * Avoid using marketing words in the user doc. Try to be terse and direct to describe the feature.
> > 
> > @adela-bytebase @LucyLu8L @raytian03
> 
> The document is translated at the [Google docs](https://docs.google.com/document/d/1yzFveIxJccfTg8YLnA7GROE0j6Aw5NUJGvHzcVo7fcM/edit#heading=h.g2tv1ds4g50f), maybe next time, we discuss on the google docs, and in here, we only need to paste the result.

Smaller change does not require this. But for change like this PR, the sanity check is helpful to avoid those common themes. @adela-bytebase please define a policy.

2022-04-08 07:36 UTC, tianzhou commented
Any update for this PR?

2022-04-08 09:09 UTC, xiaoluoboding commented
PTAL

2022-04-08 09:43 UTC, tianzhou commented
@xiaoluoboding there are a couple of suggested edits unresolved. Could you please take a look?

2022-04-08 09:44 UTC, adela-bytebase commented on docs/features/sql-editor/writing-a-query.md
> +title: Writing a Query
or at least Write a Query

2022-04-08 09:59 UTC, adela-bytebase requested changes
Let's keep the titles more like "A B to C" instead "A b to c"

2022-04-08 09:59 UTC, adela-bytebase commented on pages/index.vue
>                  alt="Never miss your work"
Never Miss your Work

2022-04-08 10:27 UTC, xiaoluoboding commented
PTAL

2022-04-08 10:38 UTC, tianzhou approved these changes
LGTM

2022-04-08 10:39 UTC, adela-bytebase approved these changes
LGTM

2022-04-08 10:45 UTC, merged