docs:add schema-sync blog
bytebase/bytebase.com pull request #653
Opened 2022-11-25 06:05 UTC by adela-bytebase

2022-11-25 10:45 UTC, tianzhou requested changes

2022-11-25 10:45 UTC, tianzhou commented on content/blog/database-schema-synchronization-in-5-mins.md
> +Bytebase's database **schema synchronization** feature (introduced in [v1.8.0](/changelog/bytebase-1-8-0)） supports copying a specific version of schema from one database to another. Without this fea
```suggestion
Bytebase's database **schema synchronization** feature (introduced in [1.8.0](/changelog/bytebase-1-8-0)） supports copying a specific schema version from one database to another. Without this feature, developers have to write SQL statements cautiously and apply them manually; Now with this feature, they can simply tell Bytebase which database schema needs to be replicated to the target database, and the whole process can be done from UI. This feature can solve the following scenarios:
```

2022-11-25 10:45 UTC, tianzhou commented on content/blog/database-schema-synchronization-in-5-mins.md
> +1) Manual modification by humans due to special ad-hoc reasons - causes database schema drift, which needs to renormalize.
```suggestion
1) Manual modification by humans due to special ad-hoc reasons - causes database schema drift, which needs reconciliation.
```

2022-11-25 10:45 UTC, tianzhou commented on content/blog/database-schema-synchronization-in-5-mins.md
> +2) The vendor maintains multiple versions of the product, so it also needs to normalize the schema.
```suggestion
2) The vendor maintains multiple product versions, so it also needs to reconcile the schema.
```

2022-11-25 10:45 UTC, tianzhou commented on content/blog/database-schema-synchronization-in-5-mins.md
> +From Bytebase [v1.8.0](/changelog/bytebase-1-8-0), you can run a 14-day **Team Plan** trial without hub registration. While having **Team Plan** trial, you can upgrade to the **Enterprise Plan** tria
```suggestion
From Bytebase [1.8.0](/changelog/bytebase-1-8-0), you can run a 14-day **Team Plan** trial without hub registration. While having **Team Plan** trial, you can upgrade to the **Enterprise Plan** trial by clicking **Upgrade** in a specific feature.
```

2022-11-25 10:45 UTC, tianzhou commented on content/blog/database-schema-synchronization-in-5-mins.md
> +With **Free** or **Team Plan**, you can only choose the latest version of history; Only with **Enterprise Plan** can you freely choose from the full migration history.
```suggestion
In Bytebase **Free** or **Team Plan**, you can choose the latest history version; In **Enterprise Plan** , you can choose an arbitrary schema version from the full migration history.
```

2022-11-25 10:45 UTC, tianzhou commented on content/blog/database-schema-synchronization-in-5-mins.md
> +title: Database Schema Synchronization in 5 mins
How to synchronize database schemas

and let's change the URL accordingly.

2022-11-29 02:21 UTC, boojack commented on pnpm-lock.yaml
> +lockfileVersion: 5.3
Unexpected change

2022-11-29 07:37 UTC, adela-bytebase commented
PTAL

2022-11-29 07:43 UTC, tianzhou approved these changes
LGTM

2022-11-29 07:43 UTC, merged