docs: post how does sync schema work in Bytebase blog
bytebase/bytebase.com pull request #656
Opened 2022-11-27 07:54 UTC by h3n4l

2022-11-27 08:43 UTC, tianzhou requested changes

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +title: How does sync schema work in Bytebase
How schema sync works in Bytebase

how-schema-sync-work

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +description: Technical contents of Bytebase sync schema for MySQL.
```suggestion
description: Technical details about how Bytebase implements schema synchronization for MySQL.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +Schema synchronization can calculate the difference between two databases and give the SQLs, which can migrate to let the schema be the same as the destination database. People do not need to write t
```suggestion
Schema synchronization can calculate the difference between two database schemas, and generate the SQL statements representing the diffs. Thus, people do not need to write the migration SQL statements by hand.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +## What is schema synchronization?
```suggestion
## What is Schema Synchronization?
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +Bytebase has supported MySQL schema synchronization since v1.8.0. The data pipeline for this module in Bytebase is shown as follows.
```suggestion
Bytebase has supported MySQL schema synchronization since v1.8.0. Below is the workflow.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +Bytebase can dump the database schema and process them into [abstract syntax tree (AST)](https://en.m.wikipedia.org/wiki/Abstract_syntax_tree) via a parser.
```suggestion
Bytebase first dumps the database schema and converts them into [abstract syntax tree (AST)](https://en.m.wikipedia.org/wiki/Abstract_syntax_tree) via the parser.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +We can get object properties in AST. Compare two corresponding entities (which may not exist). The following chart shows a simple example:
```suggestion
Bytebase then walks through the ASTs for both database schemas and compares two corresponding entities (which may not exist) from ASTs. The following chart shows a simple example:
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +### Safe Order
```suggestion
### Handle Dependencies
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +There are many dependencies between database objects, like constraints depending on indices and columns, and columns depending on the table. We need to deal with them according to the topological ord
```suggestion
There are many dependencies between database objects, like constraints depending on indices and columns, and columns depending on the table. We need to deal with them according to the topological order. The creating order must follow the below list, and the deleting order should follow the reverse order:
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +Function, trigger, and procedure do not validate at creation time, so we can create them anywhere after deleting them.
```suggestion
Function, trigger, and procedure are not validated at creation time, so we can create them anywhere after deleting them.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +Function, trigger, and procedure do not validate at creation time, so we can create them anywhere after deleting them.
I don't get this sentence BTW.

What does "them" refer to?

What is "create after deleting"?

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +Also, we should focus on the dependencies between operation types. The below list shows the ordering:
```suggestion
Also, we should sort dependencies among operation types. Below lists the ordering:
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +1. Additions for new nodes, like adding a new column.
```suggestion
1. New node creation, like adding a new column.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +2. Updates for in-place node updates like changing an existing table option.
```suggestion
2. In-place node updates, like changing an existing table definition.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +3. Deletions for destructive node updates. Because we cannot update some nodes in- place like indexes, we should drop the original one and create the new one instead.
```suggestion
3. Deletion triggered destruction node updates. Because we cannot update some nodes in place like indexes, we should drop the original one and create the new one instead.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +4. Additions for destructive node updates.
```suggestion
4. Addition triggered destructive node updates.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +5. Deletions for deleted nodes.
```suggestion
5. Node deletion.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +This sequence is correct in most cases.
this sentence seems to be redundant.

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +Now, we get a lot of ASTs. Let’s convert them to SQLs.
```suggestion
After, we get the processed ASTs, we convert them back to SQLs.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +3. Adjust diff result orders.
3 and 4 needs to mention AST as well, since we are working on AST

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +You can visit [Bytebase marketing site](https://www.bytebase.com/docs/change-database/synchronize-schema) to learn more about using synchronizing schema.
```suggestion
You can follow [docs](/docs/change-database/synchronize-schema) to learn more about using synchronizing schema.
```

2022-11-27 08:43 UTC, tianzhou commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +If you find this article helpful, you might also be interested in our product [Bytebase](https://bytebase.com/), a Database CI/CD tool for DevOps teams, built for Developers and DBAs, which is the on
This sentence is only needed for articles not relevant to our product (e.g. those tagged with Industry). Not the case for this post

2022-11-27 13:13 UTC, h3n4l commented on content/blog/how-does-sync-schema-work-in-Bytebase.md
> +Function, trigger, and procedure do not validate at creation time, so we can create them anywhere after deleting them.
How about now?

2022-11-27 13:15 UTC, h3n4l commented
PTAL @tianzhou

2022-11-27 14:00 UTC, tianzhou approved these changes
LGTM

2022-11-28 06:16 UTC, adela-bytebase approved these changes
LGTM

2022-11-28 06:20 UTC, merged