feat: schema system
bytebase/bytebase.com pull request #67
Opened 2022-04-06 02:28 UTC by ecmadao

https://user-images.githubusercontent.com/10706318/161883490-eabfe62c-61ae-494f-a04a-0001d6407320.mp4

TODO:

- Ensure the UX
- Update the rule id

2022-04-06 03:27 UTC, tianzhou commented
Please hold on to reviewing it. I will make some notes

2022-04-06 14:14 UTC, ecmadao commented
<img width="1667" alt="图片" src="https://user-images.githubusercontent.com/10706318/161995331-7d011818-c6b7-4a00-9cc1-58b2db2469ed.png">

2022-04-06 15:29 UTC, tianzhou requested changes

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    dbVersion: "8.0.28",
Let's not worry about dbversion for now. These rules should be applicable to all supported db versions in Bytebase

2022-04-06 15:29 UTC, tianzhou commented on components/SchemaSystem/SchemaRuleConfig.vue
> +          <Selecter
The switch between error and warning could be inline instead of requiring to open a new modal.

Also we can add a third option "Disable", thus we can have an inline radio group "Error", "Warn", "Disable". Thus user can quickly tweak the rules.

On the other hand, for specifying format, required columns etc, we still require the modal.

2022-04-06 15:29 UTC, tianzhou commented on components/SchemaSystem/SchemaConfigurationPage.vue
> +    <div class="lg:grid lg:grid-cols-6 lg:gap-x-8">
Let's include a Category filter, the categories.

1. Common
2. MySQL
3. Error
4. Warn
5. Disabled

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.engine.use-innodb",
engine.mysql.use-innodb

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.table.naming-convention",
naming.table

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.table.require-pk",
table.require-pk

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.column.naming-convention",
naming.column

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.table.naming-convention",
Let's put naming into a separate category since naming is important and (hard)

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.column.required-columns",
column.required

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.column.not-allow-null",
column.no-null

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.index.naming-convention",
naming.index

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.select.no-select-all",
query.select.no-select-all

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.select.require-where",
query.where.require

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.where.no-left-like",
query.where.no-leading-wildcard-like

2022-04-06 15:29 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "mysql.where.no-all-like",
This can be merged with the above one

2022-04-07 01:16 UTC, ecmadao commented on pages/database-review-guide/index.vue
> +            require(`~/assets/schema-system/${guideline.id.toLowerCase()}.webp`)
How about 
<img width="1349" alt="图片" src="https://user-images.githubusercontent.com/10706318/162100678-359731c5-bf1b-431e-9220-a30cab4a8f56.png">

2022-04-07 01:57 UTC, tianzhou commented on pages/database-review-guide/index.vue
> +            require(`~/assets/schema-system/${guideline.id.toLowerCase()}.webp`)
Some suggestions

1. Center the image
2. MySQL guideline for prod -> Guideline for Prod
3. No need to use bold for text
4. Add a border around the button

2022-04-07 02:00 UTC, tianzhou commented on pages/database-review-guide/index.vue
> +            require(`~/assets/schema-system/${guideline.id.toLowerCase()}.webp`)
I am also thinking to remove the illustration on the top right and use the below mockup

![8061649231410_ pic](https://user-images.githubusercontent.com/230323/162105109-d5fa7bb2-2a62-4ce2-bb1e-d2cc1201c854.jpg)

Without the illustration, we can center the text and let the user focus on the content.

2022-04-07 08:21 UTC, ecmadao commented on components/SchemaSystem/SchemaConfigurationPage.vue
> +                @click="onRuleSelect(rule)"
Updated. But I'm not sure if this could be too unclear for users about how to edit the rule.

2022-04-07 08:26 UTC, ecmadao commented on components/SchemaSystem/SchemaConfigurationPage.vue
> +    <div class="lg:grid lg:grid-cols-6 lg:gap-x-8">
I'm confused about the category definition. Currently the category for each rule could be "database", "naming", etc.
Seems the filter should be:
<img width="1391" alt="图片" src="https://user-images.githubusercontent.com/10706318/162155110-50972fa5-0d63-4383-930b-7a168844b02b.png">
?

2022-04-07 08:27 UTC, ecmadao commented on pages/database-review-guide/index.vue
> +            require(`~/assets/schema-system/${guideline.id.toLowerCase()}.webp`)
Updated.
<img width="1859" alt="图片" src="https://user-images.githubusercontent.com/10706318/162155322-e3e6c291-943b-4a50-b9a9-97e8c7ecefde.png">

2022-04-07 10:05 UTC, ecmadao commented on components/SchemaSystem/SchemaRuleConfig.vue
> +          <Selecter
Do you mean this way?

<img width="1028" alt="图片" src="https://user-images.githubusercontent.com/10706318/162175345-e5c2f65c-16c1-440f-871d-82a2be88f0fc.png">

I'm not sure if this would be a little annoying as there could be too many radio box

2022-04-07 10:24 UTC, tianzhou commented on components/SchemaSystem/SchemaConfigurationPage.vue
> +    <div class="lg:grid lg:grid-cols-6 lg:gap-x-8">
Oh sorry about the confusion. I meant the "tag" added to each rule, so "filter" is a better word indeed. Let's keep the category for the "Rule"

2022-04-07 10:25 UTC, tianzhou commented on components/SchemaSystem/SchemaConfigurationPage.vue
> +    <div class="lg:grid lg:grid-cols-6 lg:gap-x-8">
So essentially, we have 2 different group types. One is the "Tag", and the other is the rule category. I meant to create a filter for the former case.

2022-04-07 10:28 UTC, tianzhou commented on components/SchemaSystem/SchemaRuleConfig.vue
> +          <Selecter
Indeed. Let's keep it in the modal then.

2022-04-07 11:54 UTC, ecmadao commented
https://user-images.githubusercontent.com/10706318/162192876-79ee3efe-b444-4a16-87ce-75ef43a6b8e5.mp4

The online demo: https://bytebase-com-pr-67.onrender.com/database-review-guide

2022-04-07 11:56 UTC, ecmadao commented on common/schemaSystem.ts
> +    ].reduce((res, id) => {
PTAL for rule description and the guideline template @tianzhou @d-bytebase

2022-04-07 13:14 UTC, tianzhou requested changes

2022-04-07 13:14 UTC, tianzhou commented on common/schemaSystem.ts
> +    description: "Columns cannot allow null value",
```suggestion
    description: "Columns cannot have NULL value.",
```

2022-04-07 13:14 UTC, tianzhou commented on common/schemaSystem.ts
> +    description: "Not allow 'SELECT *'",
```suggestion
    description: "Disallow 'SELECT *'.",
```

2022-04-07 13:14 UTC, tianzhou commented on common/schemaSystem.ts
> +    description: "Query must contains 'WHERE' limit",
```suggestion
    description: "Require 'WHERE' clause.",
```

2022-04-07 13:14 UTC, tianzhou commented on common/schemaSystem.ts
> +    description: "Not allow '%x' in LIKE",
```suggestion
    description: "Disallow leading '%' in LIKE, e.g. LIKE foo = '%bar' is not allowed.",
```

2022-04-07 13:19 UTC, tianzhou commented on pages/database-review-guide/index.vue
> +        is a online tool to create the schema review guideline for your database.
Let's just say "An online tool for DBA to generate the database schema review / DDL guideline. Support MySQL now, PostgreSQL later."

2022-04-07 13:19 UTC, tianzhou commented on pages/database-review-guide/index.vue
> +        is a online tool to create the schema review guideline for your database.
Hope this helps SEO.

2022-04-07 13:25 UTC, tianzhou requested changes

2022-04-07 13:25 UTC, tianzhou commented on components/SchemaSystem/SchemaSystemPreview.vue
> +        Made by
```suggestion
        Made from
```

2022-04-07 13:25 UTC, tianzhou commented on components/SchemaSystem/SchemaSystemPreview.vue
> +          bytebase.com/database-review-guide
```suggestion
          https://bytebase.com/database-review-guide
```

2022-04-07 13:25 UTC, tianzhou commented on components/SchemaSystem/SchemaSystemPreview.vue
> +          bytebase.com/database-review-guide
How about adding a date?

2022-04-07 13:25 UTC, tianzhou commented on components/SchemaSystem/SchemaSystemPreview.vue
> +  </div>
If it's not hard, we can add a footer with the Bytebase logo at the bottom right.

2022-04-07 13:25 UTC, tianzhou commented on components/SchemaSystem/SchemaSystemPreview.vue
> +    </div>
![CleanShot 2022-04-07 at 21 23 58](https://user-images.githubusercontent.com/230323/162209208-766155dd-5038-4d54-971f-09bdb690bcc4.png)

need to expand the width a bit to avoid wrapping

2022-04-08 01:19 UTC, ecmadao commented on components/SchemaSystem/SchemaSystemPreview.vue
> +  </div>
How about adding the logo and creation date at the bottom?
<img width="872" alt="图片" src="https://user-images.githubusercontent.com/10706318/162344461-66970b1a-f0c4-4c0a-9002-679f1e3bb5de.png">

2022-04-08 07:58 UTC, tianzhou requested changes

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +  rules: SelectedRule[];
ruleList, use xxxList for array type across our codebase

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +  title: string;
name

For consistency, we usually have "name" and "description"

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +    category: "database",
category maybe "engine" ?

"database" can reserved for common "database" setting (similar to table, column). While here we are talking about "MySQL", "Postgres" specific stuff.

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +    description: "Limit the primary key name format",
```suggestion
    description: "Enforce the primary key name format.",
```

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +    description: "Limit the unique key name format",
```suggestion
    description: "Enforce the unique key name format.",
```

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +    description: "Limit the index name format",
```suggestion
    description: "Enforce the index name format.",
```

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "MySQL-Prod",
mysql.prod

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "MySQL-Dev",
mysql.dev

2022-04-08 07:58 UTC, tianzhou commented on common/schemaSystem.ts
> +    id: "MySQL-Prod",
reverse domain name notation is our good friend https://en.wikipedia.org/wiki/Reverse_domain_name_notation

2022-04-08 07:58 UTC, tianzhou commented on components/Icons/CheckCircle.vue
> +<template>
Use https://sourcegraph.com/search?q=context:%40bytebase+heroicons-outline&patternType=literal ?

2022-04-08 07:58 UTC, tianzhou commented on pages/database-review-guide/index.vue
> +    onRuleRemove(rule: SelectedRule) {
I would remove the rule add/remove UX and logic

2022-04-08 07:59 UTC, tianzhou commented on pages/database-review-guide/index.vue
> +            require(`~/assets/schema-system/${guideline.id.toLowerCase()}.webp`)
As the rule order let's use

Engine
Naming
Query
Table
Column

2022-04-08 08:00 UTC, tianzhou commented
Also for the arrayType, let's use xxxList for consistence across the codebase

2022-04-08 08:17 UTC, ecmadao commented on components/Icons/CheckCircle.vue
> +<template>
We don't install the hero icon in this repo, some dependencies and configuration also need to update to align with the console. We can do this in another PR.

2022-04-08 08:31 UTC, ecmadao commented on pages/database-review-guide/index.vue
> +    onRuleRemove(rule: SelectedRule) {
Removed

2022-04-08 09:59 UTC, tianzhou requested changes

2022-04-08 09:59 UTC, tianzhou commented on components/SchemaSystem/SchemaSystemPreview.vue
> +        Made from
Is it possible to only include this when generating the image?

2022-04-08 09:59 UTC, tianzhou commented on components/SchemaSystem/SchemaConfigurationPage.vue
> +            v-for="(category, index) in categoryList"
Category order:

Engine
Naming
Query
Table
Column

2022-04-08 09:59 UTC, tianzhou commented
@LiuJi-Jim PTAL

2022-04-08 10:00 UTC, tianzhou commented on components/SchemaSystem/SchemaConfigurationPage.vue
> +            v-for="(category, index) in categoryList"
The rationale is:

Engine is special, so put it first
Naming is important
Query is more commonly used than Table/Column

2022-04-08 12:48 UTC, ecmadao commented on components/SchemaSystem/SchemaSystemPreview.vue
> +        Made from
Sure, updated. PTAL https://bytebase-com-pr-67.onrender.com/database-review-guide

2022-04-08 14:06 UTC, ecmadao commented on components/SchemaSystem/SchemaConfigurationPage.vue
> +            v-for="(category, index) in categoryList"
Updated

2022-04-09 03:08 UTC, tianzhou commented on components/SchemaSystem/SchemaSystemPreview.vue
> +        Made from
Still seeing it

![CleanShot 2022-04-09 at 11 07 43@2x](https://user-images.githubusercontent.com/230323/162554149-fa62eae6-d020-4e8f-bb8f-df6220f8e9c0.png)

2022-04-09 16:20 UTC, ecmadao commented on components/SchemaSystem/SchemaSystemPreview.vue
> +        Made from
Oh I just thought you mean the logo at the bottom. Updated.

2022-04-11 03:19 UTC, boojack commented on components/InputWithTemplate/InputWithTemplate.vue
> +  methods: {
Maybe we should put `methods`, `created`, `unmounted`... into `setup` to avoid using `this`.

2022-04-11 07:44 UTC, tianzhou submitted a review, later dismissed
LGTM.

2022-04-11 12:20 UTC, ecmadao commented on components/InputWithTemplate/InputWithTemplate.vue
> +  methods: {
Code style updated, PTAL.

2022-04-11 12:37 UTC, boojack approved these changes
LGTM

2022-04-12 02:07 UTC, tianzhou approved these changes
LGTM

2022-04-12 02:09 UTC, merged