docs: upload tute for setting up sql review ci
bytebase/bytebase.com pull request #675
Opened 2022-12-02 06:54 UTC by milasuperstar

chinese version at: https://mp.weixin.qq.com/s/-E0oTa0R23OGV7OyieQIvQ

2022-12-02 07:40 UTC, adela-bytebase commented on content/blog/sql-review-ci-tute.md
> +## Step 1. Configure SQL review CI
Step 1 - Configure SQL review CI

2022-12-02 09:44 UTC, tianzhou requested changes

2022-12-02 09:44 UTC, tianzhou commented on content/blog/sql-review-ci-tute.md
> +title: Integrating SQL Review into Your GitLab & GitHub CI/CD
how-to-integrate-sql-review-into-gitlab-github-ci. (because that's more SEO friendly)

How to integrate SQL Review into Your GitLab / GitHub CI

Remove CD part from all other places as well.

2022-12-02 09:44 UTC, tianzhou commented on content/blog/sql-review-ci-tute.md
> +title: Integrating SQL Review into Your GitLab & GitHub CI/CD
GitLab/GitHub only plays the CI role here. CD means continuous deployment which is a different thing from CI (Continuous Integration).

2022-12-02 09:44 UTC, tianzhou commented on content/blog/sql-review-ci-tute.md
> +To accommodate to the different ways different development teams work, Bytebase offers multiple ways to integrate SQL Review into your workflow.
```suggestion
Different development teams adopt different development workflow, and Bytebase offers multiple ways to integrate SQL Review into their respective workflows.
```

2022-12-02 09:44 UTC, tianzhou commented on content/blog/sql-review-ci-tute.md
> +This feature requires the team plan. (Starting from v1.8.0, you can start a 14-day team plan trial without registration!)
It's enterprise plan only

2022-12-02 09:44 UTC, tianzhou commented on content/blog/sql-review-ci-tute.md
> +![_](/static/blog/sql-review-ci-tute/gha-sql-review-details.webp)
This is a GitHub screenshot.

2022-12-02 09:44 UTC, tianzhou commented on content/blog/sql-review-ci-tute.md
> +- GitHub App: 0 codings required.
```suggestion
- [GitHub App](https://github.com/marketplace/bytebase): Zero code configuration.
```

2022-12-02 10:18 UTC, adela-bytebase commented on content/blog/sql-review-ci-tute.md
> +title: Integrating SQL Review into Your GitLab & GitHub CI/CD
But CI/CD is better for SEO?

2022-12-05 12:19 UTC, tianzhou commented on content/blog/sql-review-ci-tute.md
> +title: Integrating SQL Review into Your GitLab & GitHub CI/CD
I see

2022-12-06 03:16 UTC, milasuperstar commented on content/blog/sql-review-ci-tute.md
> +title: Integrating SQL Review into Your GitLab & GitHub CI/CD
I've renamed the title to "How to integrate SQL Review into Your GitLab or GitHub CI/CD", tag is "how-to-integrate-sql-review-into-gitlab-github-ci"

2022-12-06 03:16 UTC, milasuperstar commented on content/blog/sql-review-ci-tute.md
> +![_](/static/blog/sql-review-ci-tute/gha-sql-review-details.webp)
moved the screenshot down a section :)

2022-12-06 03:16 UTC, milasuperstar commented on content/blog/how-to-integrate-sql-review-into-gitlab-github-ci.md
> +This feature requires the [Enterprise Plan](https://www.bytebase.com/pricing). (Starting from v1.8.0, you can start a 14-day team plan trial without registration!)
how do i link to the pricing page w/o using the bytebase.com prefix?

2022-12-06 03:43 UTC, tianzhou requested changes

2022-12-06 03:43 UTC, tianzhou commented on content/blog/how-to-integrate-sql-review-into-gitlab-github-ci.md
> +Bytebase now supports integrating SQL review CI into your preferred code repository, whether it be GitHub or GitLab. In addition, for GitHub, Bytebase provides [additional ways](/docs/sql-review/sql-
```suggestion
Bytebase now supports integrating SQL review CI into your preferred code repository, whether it be GitHub or GitLab. In addition, for GitHub, Bytebase provides [additional ways](/docs/sql-review/sql-advisor/overview) to integrate SQL Review through:
```

2022-12-06 03:43 UTC, tianzhou commented on content/blog/how-to-integrate-sql-review-into-gitlab-github-ci.md
> +## Step 2 - SQL Review is Triggered Automatically
```suggestion
## Step 2 - Create an MR/PR to Trigger SQL Review
```

2022-12-06 03:43 UTC, tianzhou commented on content/blog/how-to-integrate-sql-review-into-gitlab-github-ci.md
> +Once you've set up the CI, the SQL review policy will be automatically triggered to check against each MR that contains SQL script files.
```suggestion
Once you've set up the CI, if you create a GitLab MR / GitHub PR that contains the files matching [the file path template](/docs/vcs-integration/name-and-organize-schema-files#file-path-template), the SQL review policy will be automatically triggered to check against the changes.
```

2022-12-06 03:43 UTC, tianzhou commented on content/blog/how-to-integrate-sql-review-into-gitlab-github-ci.md
> +Similarly, in GitHub repos, SQL review will check for changes that match [the file path template](/docs/vcs-integration/name-and-organize-schema-files#file-path-template) through GitHub Actions.
```suggestion
Similarly, in GitHub repos, SQL review will check against the changes through GitHub Actions.
```

2022-12-06 14:32 UTC, adela-bytebase commented on content/blog/how-to-integrate-sql-review-into-gitlab-github-ci.md
> +This feature requires the [Enterprise Plan](https://www.bytebase.com/pricing). (Starting from v1.8.0, you can start a 14-day team plan trial without registration!)
> how do i link to the pricing page w/o using the bytebase.com prefix?

You can use  /pricing

2022-12-07 02:54 UTC, milasuperstar commented on content/blog/how-to-integrate-sql-review-into-gitlab-github-ci.md
> +This feature requires the [Enterprise Plan](https://www.bytebase.com/pricing). (Starting from v1.8.0, you can start a 14-day team plan trial without registration!)
> > how do i link to the pricing page w/o using the bytebase.com prefix?
> 
> You can use /pricing

tried and it didn't work in preview :(

2022-12-07 06:53 UTC, tianzhou approved these changes
LGTM. Let's update the pricing link

2022-12-07 09:51 UTC, tianzhou approved these changes
LGTM. Please resolve the conflict

2022-12-07 10:06 UTC, merged