docs: blog - three Ways to Integrate Automatic SQL Review into GitHub
bytebase/bytebase.com pull request #688
Opened 2022-12-08 10:33 UTC by tianzhou

2022-12-09 06:57 UTC, milasuperstar requested changes

2022-12-09 06:57 UTC, milasuperstar commented on content/blog/integrate-sql-review-into-github.md
> +going live, making it difficult to ensure the quality of changes.
```suggestion
the changes go live, leaving the DBAs minimal time to review the scripts (or request changes), making it difficult to ensure the quality of changes.
```

2022-12-09 06:57 UTC, milasuperstar commented on content/blog/integrate-sql-review-into-github.md
> +1. Customizing SQL Review rules
```suggestion
1. Customizing SQL Review rules

```

2022-12-09 06:57 UTC, milasuperstar commented on content/blog/integrate-sql-review-into-github.md
> +   This mode requires the deployment of Bytebase Console and import the database enviornment into it.
```suggestion
   This mode requires the deployment of Bytebase Console, and you need to import your database environment into Bytebase.
```

2022-12-09 06:57 UTC, milasuperstar commented on content/blog/integrate-sql-review-into-github.md
> +   If you are not satisfied with the default SQL Review rules, you can configure it visually in the
```suggestion
   If you are not satisfied with the default SQL Review rules, you can configure it visually from the
```

2022-12-09 06:57 UTC, milasuperstar commented on content/blog/integrate-sql-review-into-github.md
> +| For                   | **Personal and small teams**  | **Personal and small teams**                  | **Teams needing complete database change management**              |
is it better to use "individual" here instead of personal?

2022-12-09 11:19 UTC, tianzhou commented on content/blog/integrate-sql-review-into-github.md
> +| For                   | **Personal and small teams**  | **Personal and small teams**                  | **Teams needing complete database change management**              |
```suggestion
| For                   | **Individual and small teams**  | **Individual and small teams**                  | **Teams needing complete database change management**              |
```

2022-12-09 11:19 UTC, tianzhou commented on content/blog/integrate-sql-review-into-github.md
> +| For                   | **Personal and small teams**  | **Personal and small teams**                  | **Teams needing complete database change management**              |
True

2022-12-09 11:20 UTC, tianzhou commented
PTAL

2022-12-10 15:03 UTC, merged

2022-12-10 15:04 UTC, tianzhou commented
Submit now. I will address more comments in separate PR