feat: update external approval, manually trigger
bytebase/bytebase.com pull request #690
Opened 2022-12-09 07:18 UTC by RainbowDashy

Update external approval docs:

- Users need to trigger sending external approvals in the UI workflow manually.
- External approvals are sent in the GitOps workflow automatically.

2022-12-09 08:01 UTC, ecmadao approved these changes

2022-12-09 11:13 UTC, tianzhou requested changes

2022-12-09 11:13 UTC, tianzhou commented on content/docs/administration/webhook-integration/external-approval.md
> +The issue creator needs to click on the bell button near the assignee to send the Feishu approval.
```suggestion
The issue creator needs to click on the bell button near the assignee to send the Feishu approval request.
```

2022-12-09 11:13 UTC, tianzhou commented on content/docs/administration/webhook-integration/external-approval.md
> +The Feishu approval is sent automatically.
automatically when?

2022-12-12 05:29 UTC, RainbowDashy commented on content/docs/administration/webhook-integration/external-approval.md
> +The Feishu approval is sent automatically.
```suggestion
The Feishu approval is sent automatically when we arrive at a new stage or either of the assignee and the SQL statement has changed.
```

2022-12-12 05:52 UTC, tianzhou requested changes

2022-12-12 05:52 UTC, tianzhou commented on content/docs/administration/webhook-integration/external-approval.md
> +The Feishu approval is sent automatically when we arrive at a new stage or either of the assignee and the SQL statement has changed.
```suggestion
The Feishu approval is sent automatically when either of the following happens:
- Arrive at a new stage.
- Assignee has changed.
- SQL statement has changed.
```

2022-12-12 05:53 UTC, tianzhou commented on content/docs/administration/webhook-integration/external-approval.md
> +The Feishu approval is sent automatically when we arrive at a new stage or either of the assignee and the SQL statement has changed.
Be clear, then shorten. Not the other way around.

2022-12-12 06:07 UTC, RainbowDashy commented on content/docs/administration/webhook-integration/external-approval.md
> +- SQL statement has changed.
```suggestion
- Issue arrives at a new stage.
- Issue assignee has changed.
- Task SQL statement has changed.
```

2022-12-12 06:09 UTC, tianzhou approved these changes
LGTM

2022-12-12 06:14 UTC, merged