docs: user doc for UI editor(WIP)
bytebase/bytebase.com pull request #692
Opened 2022-12-12 10:03 UTC by boojack

2022-12-12 16:59 UTC, tianzhou requested changes
Change UI Editor to Schema Editor for the doc and blog post.

Missing the layout entry.

@candy2255 also, l am thinking we should rename this project to Schema Editor internally as well.

2022-12-12 16:59 UTC, tianzhou commented on content/docs/change-database/ui-based-schema-editor.md
> +title: UI Editor
```suggestion
title: Schema Editor
```

2022-12-12 16:59 UTC, tianzhou commented on content/docs/change-database/ui-based-schema-editor.md
> +Bytebase's UI Editor is a modern, friendly tool with an elegant UI that allows you to view and edit database structure in a simple and clean spreadsheet-like editor. Any changes in UI Editor will not
```suggestion
Bytebase's Schema Editor provides a spreadsheet-like editor to view and edit database structure. Users first use the Schema Editor to prepare the schema changes, then those changes will be converted into SQL statements and go through the change workflow.
```

2022-12-12 16:59 UTC, tianzhou commented on content/docs/change-database/ui-based-schema-editor.md
> +1. Click the **New Table** on the top of table list in database tab.
```suggestion
1. Select a database and click the **New Table** on the top of the table list tab.
```

2022-12-12 16:59 UTC, tianzhou commented on content/docs/change-database/ui-based-schema-editor.md
> +1. Add new column by clicking the **Add Column** on the top of column list.
```suggestion
1. Add new column by clicking the **Add Column** on the top of column list tab.
```

2022-12-12 16:59 UTC, tianzhou commented on content/docs/change-database/ui-based-schema-editor.md
> +By clicking on **Alter Schema** in the Quick Action panel and selecting the database, you will see the UI Editor dialog.
```suggestion
By clicking on **Alter Schema** in the Quick Action panel and selecting the database, you will see the Schema Editor dialog.
```

2022-12-12 16:59 UTC, tianzhou commented on content/docs/change-database/ui-based-schema-editor.md
> +1. Hover and click the **Drop Table** dropdown item in database item, or the **Drop Table** in database tab.
```suggestion
1. Hover to the table and click the **Drop Table** dropdown item, or the **Trash** button for the table row.
```

2022-12-13 06:42 UTC, adela-bytebase commented on content/docs/change-database/schema-editor.md
> +<hint-block type="warning">
Let's do "info" instead of "warning" block
https://github.com/bytebase/bytebase/blob/main/docs/writing-guide.md

2022-12-13 07:12 UTC, boojack commented on content/docs/change-database/schema-editor.md
> +<hint-block type="warning">
Done

2022-12-13 07:56 UTC, candy2255 approved these changes
LGTM

2022-12-14 09:33 UTC, boojack commented
PTAL

2022-12-14 09:41 UTC, tianzhou approved these changes
LGTM

2022-12-14 09:41 UTC, tianzhou commented on content/docs/change-database/schema-editor.md
> +Bytebase's Schema Editor provides a spreadsheet-like editor to view and edit database structure. Users first use the Schema Editor to prepare the schema changes, then those changes will be converted
```suggestion
Bytebase's Schema Editor provides a spreadsheet-like editor to view and edit database structure. Users first use the Schema Editor to prepare the schema changes, then those changes will be converted into SQL statements and go through the [change workflow](/docs/change-database/change-workflow).
```

2022-12-14 10:17 UTC, merged