Add admin mode blog
bytebase/bytebase.com pull request #698
Opened 2022-12-14 07:11 UTC by adela-bytebase

2022-12-14 08:24 UTC, tianzhou requested changes

2022-12-14 08:24 UTC, tianzhou commented on content/blog/change-schema-sql-editor-admin-mode-vs-readonly-mode.md
> +description: This article will give you step-by-step guidance for SQL Editor, to change schema using Admin Mode and Read-only Mode. 5 mins is more than enough.
can make the description more terse.

Something like "Step-by-step guide for using SQL Editor in read-only and admin mode"

2022-12-14 08:24 UTC, tianzhou commented on content/blog/change-schema-sql-editor-admin-mode-vs-readonly-mode.md
> +After resolve the auto-generated issue, database **db-test** is created successfully.
```suggestion
After resolving the auto-generated issue, database **db-test** is created successfully.
```

2022-12-14 10:25 UTC, milasuperstar commented on content/blog/change-schema-sql-editor-admin-mode-vs-readonly-mode.md
> +1. In the terminal, run the following command to start a Bytebase:
```suggestion
1. In the terminal, run the following command to start Bytebase:
```

2022-12-14 10:25 UTC, milasuperstar commented on content/blog/change-schema-sql-editor-admin-mode-vs-readonly-mode.md
> +3. Open [http://localhost:5678/](http://localhost:5678/) in your browser, if you are the first to register, you’ll become **Workspace Owner** by default
```suggestion
3. Open [http://localhost:5678/](http://localhost:5678/) in your browser, if it’s the first time you register, you’ll become **Workspace Owner** by default.
```

2022-12-14 10:25 UTC, milasuperstar commented on content/blog/change-schema-sql-editor-admin-mode-vs-readonly-mode.md
> +Thus far, you’ve tried two ways in Bytebase to handle TABLE CREATE queries for DBA (Admin Mode) and developer (Readonly) respectively. Next, you can continue exploring SQL Editor modes in Bytebase, m
```suggestion
Thus far, you’ve tried two ways in Bytebase to handle CREATE TABLE queries for DBA (Admin Mode) and developer (Read-only) respectively. Next, you can continue exploring SQL Editor modes in Bytebase, maybe with your own databases and use cases. Feel free to give us your suggestions!
```

2023-01-04 06:53 UTC, Candybase approved these changes
LGTM

2023-01-05 14:53 UTC, closed without merging