docs: add blog Database Change Management with Snowflake
bytebase/bytebase.com pull request #709
Opened 2022-12-22 15:45 UTC by adela-bytebase

2022-12-22 16:04 UTC, tianzhou requested changes

2022-12-22 16:04 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +## Bonus Section - Drift Detect
```suggestion
## Bonus Section - Schema Drift Detection
```

2022-12-22 16:04 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +database DB_DEMO_BB
```suggestion
2. Wait for 10 mins or more. Go back to Bytebase, and you can find the Schema Drift on database DB_DEMO_BB
```

2022-12-22 16:04 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +Anomaly Center
```suggestion
The Anomaly Center also surfaces the drift
```

2022-12-22 16:04 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +4. Go to DB_DEMO_BB > **Migration History** and click **Establish new baseline**.
```suggestion
4. Use baseline to reconcile the schema state from the live database schema. Go to DB_DEMO_BB > **Migration History** and click **Establish new baseline**.
```

2022-12-22 16:04 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +Now you have connected snowflake with Bytebase, and tried out the UI workflow to do schema change. Bytebase will record the full migration history for you. With **Team or Enterprise Plan**, you can e
```suggestion
Now you have connected snowflake with Bytebase, and tried out the UI workflow to do schema change. Bytebase will record the full migration history for you. With **Team or Enterprise Plan**, you can even have schea drift detection.
```

2022-12-22 16:04 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +In the next article, you’ll try out GitOps workflow, which will store your Snowflake schema in GitHub and trigger the change upon committing the change to the repository, to bring your Snowflake chan
```suggestion
In the next article, you’ll try out GitOps workflow, which will store your Snowflake schema in GitHub and trigger the change upon committing the change to the repository, to bring your Snowflake change workflow to the next level of Database DevOps - [Database as Code](/blog/database-as-code).
```

2022-12-22 16:28 UTC, adela-bytebase commented on content/blog/database-change-management-with-snowflake.md
> +feature_image: /static/blog/database-change-management-with-snowflake/snowflake-db-management.webp
What should the image look like? The 1.9.1 article has a list.

2022-12-23 03:40 UTC, milasuperstar requested changes

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +Now you have connected snowflake with Bytebase, and tried out the UI workflow to do schema change. Bytebase will record the full migration history for you. With **Team or Enterprise Plan**, you can e
```suggestion
Now you have connected Snowflake with Bytebase, and tried out the UI workflow to do schema change. Bytebase will record the full migration history for you. With **Team or Enterprise Plan**, you will have drift detection.
```

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +This tutorial will guide you step-by-step to set up database change management for Snowflake in Bytebase. With Bytebase, a team can have a formalized review and rollout process to make Snowflake sche
```suggestion
This tutorial will guide you step-by-step to set up database change management for [Snowflake](https://www.snowflake.com/en/) in Bytebase. With Bytebase, a team can have a formalized review and rollout process to make Snowflake schema and data changes.
```

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +2. Follow the onboarding guide if it’s your first time running Bytebase, if not click **Add Instance**.
```suggestion
2. Follow the onboarding guide if it’s your first time running Bytebase, otherwise, simply click **Add Instance**.
```

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +**Environment**: choose `Test`, if you choose `Prod`, it will wait for approval by default. In this tutorial, we try to keep it simple. However, it’s all configurable.
```suggestion
**Environment**: choose `Test`, if you choose `Prod`, you will need approval for all future change requests. In this tutorial, let's try to keep it simple. (However, it’s all configurable later.)
```

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +**Username and password**: The ones you use to log into Snowflake.
```suggestion
**Username and password**: The ones you use to log into your Snowflake account.
```

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +3. It will create an issue “CREATE DATABASE ….” automatically. Because it’s for `Test` environment, the issue will run without waiting for your approval by default. Click **Resolve**, and the issue i
```suggestion
3. Bytebase will create an issue “CREATE DATABASE ….” automatically. Because it’s for the `Test` environment, the issue will run without waiting for your approval by default. Click **Resolve**, and the issue is Done. The database is created.
```

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +4. Go back to the home page by clicking **Home** on the left sidebar. If it’s the first time you use Bytebase, it’ll show a celebration. On the home page, you can see the project, the database, and t
```suggestion
4. Go back to the home page by clicking **Home** on the left sidebar. If it’s the first time you use Bytebase, a celebration mark will appear. On the home page, you can see the project, the database, and the issue you just resolved.
```

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +This section requires you to have **Team Plan** or **Enterprise Plan** (you can start 14 days trial directly in the product without credit card).
```suggestion
[Drift Detection]/docs/anomaly-detection/drift-detection) requires the **Team Plan** or **Enterprise Plan** (you can start 14 days trial directly in the product without a credit card).
```

2022-12-23 03:40 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +2. Wait for 10 mins or more. Go back to Bytebase, and you can find the Schema Drift on database DB_DEMO_BB
```suggestion
2. Wait a few minutes before going back to Bytebase, and you will find the Schema Drift on database DB_DEMO_BB
```

2022-12-23 06:15 UTC, adela-bytebase commented on content/blog/database-change-management-with-snowflake.md
> +2. Wait for 10 mins or more. Go back to Bytebase, and you can find the Schema Drift on database DB_DEMO_BB
@milasuperstar Bytebase does the check every 10 mins.

2022-12-23 06:20 UTC, milasuperstar commented on content/blog/database-change-management-with-snowflake.md
> +2. Wait for 10 mins or more. Go back to Bytebase, and you can find the Schema Drift on database DB_DEMO_BB
can we say "Wait for 10 mins (as Bytebase does the check every 10 mins). Go back to Bytebase, and you can find the Schema Drift on database DB_DEMO_BB"

2022-12-23 06:21 UTC, adela-bytebase commented on content/blog/database-change-management-with-snowflake.md
> +2. Wait for 10 mins or more. Go back to Bytebase, and you can find the Schema Drift on database DB_DEMO_BB
Let's do it!

2022-12-23 07:45 UTC, tianzhou approved these changes
LGTM

2022-12-23 08:36 UTC, milasuperstar approved these changes

2022-12-23 08:36 UTC, merged