Docs: Add snowflake with Bytebase and GitHub
bytebase/bytebase.com pull request #712
Opened 2022-12-26 08:48 UTC by adela-bytebase

2022-12-26 11:09 UTC, tianzhou requested changes

2022-12-26 11:09 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake-and-github.md
> +To make local-running Bytebase visible to GitHub, we’ll pass ngrok generated URL  to [--external-url](/docs/get-started/install/external-url). If you’re running Bytebase in Docker without this parame
```suggestion
To make local-running Bytebase visible to GitHub, we’ll pass ngrok‘s generated URL  to [--external-url](/docs/get-started/install/external-url). If you’re running Bytebase in Docker without this parameter (as in the previous tutorial), you can stop the running Bytebase first. The data created in the last tutorial is stored under `~/.bytebase/data` by default and will be restored if the Bytebase restarts.
```

2022-12-26 11:09 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake-and-github.md
> +7. After the OAuth application is created successfully. Click **Generate a new client secret**. Copy **Client ID** and this newly generated **Client Secret** and paste them back into Bytebase.
```suggestion
7. After the OAuth application is created successfully. Click **Generate a new client secret**. Copy **Client ID** and this newly generated **Client Secret**, then paste them back into Bytebase.
```

2022-12-26 11:09 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake-and-github.md
> +1. In your GitHub repository `snowflake-test-bb-local`, create a folder `bytebase`, then create a subfolder `test`, and create an SQL file following the pattern `{{ENV_NAME}}/{{DB_NAME}}##{{VERSION}}
```suggestion
1. In your GitHub repository `snowflake-test-bb-local`, create a folder `bytebase`, then create a subfolder `test`, and create an SQL file following the pattern `{{ENV_NAME}}/{{DB_NAME}}##{{VERSION}}##{{TYPE}}##{{DESCRIPTION}}.sql`. It is the default configuration for file path template setting when you configure the project version control previously.
```

2022-12-26 11:09 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake-and-github.md
> +- The issue is completed without manual approval because it’s on Test stage where no manual approval is required.
```suggestion
- The issue is completed without manual approval because it applies the schema change to a database from the Test environment. And our Test environment is configured with no manual approval required.
```

2022-12-26 11:09 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake-and-github.md
> +6. Let’s create another SQL file `DB_DEMO_BB##202212152040#ddl#add_age.sql`. Paste the SQL script in it.
```suggestion
6. Let’s create another SQL file `DB_DEMO_BB##202212152040#ddl#add_age.sql` to see how that latest schema file will be updated after applying a new schema change. Paste the SQL script in it.
```

2022-12-26 11:09 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +<<<<<<< HEAD
Unexpected change

2022-12-26 11:09 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake-and-github.md
> +Now you have tried out **GitOps workflow**, which will store your Snowflake schema in GitHub and trigger the change upon committing the change to the repository, to bring your Snowflake change workfl
```suggestion
Now you have tried out **GitOps workflow**, which will store your Snowflake schema in GitHub and trigger the change upon committing the change to the repository, to bring your Snowflake change workflow to the next level of Database DevOps - [**Database as Code**](/blog/database-as-code).

You can check out our [GitOps docs](docs/vcs-integration/overview) to learn more configuration details.
```

2022-12-27 06:40 UTC, tianzhou requested changes
I notice the image file name is prj, sts

Let's not do that. I even don't know what that sts mean.

2022-12-27 06:40 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +  --port 8080
Unexpected change

2022-12-27 06:40 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +<<<<<<< HEAD
Unexpected change

2022-12-27 06:41 UTC, tianzhou commented
> I notice the image file name is prj, sts
> 
> Let's not do that. I even don't know what that sts mean.

We can do this in a separate PR as we need to change multiple posts.

2022-12-27 08:19 UTC, adela-bytebase commented on content/blog/database-change-management-with-snowflake.md
> +  --port 8080
this is intended

2022-12-27 08:36 UTC, tianzhou approved these changes
LGTM

2022-12-27 08:36 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +  --port 8080
line 46 ```` should not be deleted

2022-12-27 08:36 UTC, merged