docs: Fix snowflake article
bytebase/bytebase.com pull request #714
Opened 2022-12-27 11:52 UTC by adela-bytebase

It was broken ...

2022-12-27 12:58 UTC, tianzhou requested changes
You need to sync with the head

2022-12-27 13:20 UTC, tianzhou approved these changes
LGTM

2022-12-27 13:23 UTC, tianzhou requested changes

2022-12-27 13:23 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +````
I guess we copied from 
![CleanShot 2022-12-27 at 21 23 08](https://user-images.githubusercontent.com/230323/209672941-670d468e-d2eb-4f81-a10e-115cdaca494c.png)


But that's not the typical writing.

2022-12-28 03:04 UTC, adela-bytebase commented on content/blog/database-change-management-with-snowflake.md
> +````
yes ...

2022-12-28 04:33 UTC, tianzhou approved these changes
LGTM

2022-12-28 04:33 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +);
```suggestion
````sql
CREATE SCHEMA DEMO_UI;
CREATE TABLE HELLO_WORLD
(
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR
);
````
```

2022-12-28 04:34 UTC, tianzhou commented on content/blog/database-change-management-with-snowflake.md
> +);
Need to have trailing ````

2022-12-28 05:29 UTC, merged