docs: announcement for the new SQL Editor
bytebase/bytebase.com pull request #727
Opened 2023-01-05 10:15 UTC by Candybase

The blog post introduces 3 features: the new SQL Editor, data anonymization, and database access control.

2023-01-05 11:31 UTC, tianzhou requested changes
I have tweaked some content directly. The left items is to add the audit log content.

2023-01-05 14:52 UTC, adela-bytebase commented
I can't view the image, don't know why ...

2023-01-05 14:56 UTC, tianzhou requested changes

2023-01-05 14:56 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +![admin-mode](/static/blog/the-sql-editor-for-developers-and-dbasadmin-mode.webp)
```suggestion
![admin-mode](/static/blog/the-sql-editor-for-developers-and-dbas/admin-mode.webp)
```

2023-01-05 14:56 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +![access-control](/static/blog/the-sql-editor-for-developers-and-dbasaccess-control.webp)
```suggestion
![access-control](/static/blog/the-sql-editor-for-developers-and-dbas/access-control.webp)
```

2023-01-05 14:56 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +![anonymize-data](/static/blog/the-sql-editor-for-developers-and-dbasanonymize-data.webp)
```suggestion
![anonymize-data](/static/blog/the-sql-editor-for-developers-and-dbas/anonymize-data.webp)
```

2023-01-05 14:56 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +![large-script](/static/blog/the-sql-editor-for-developers-and-dbaslarge-script.webp)
```suggestion
![large-script](/static/blog/the-sql-editor-for-developers-and-dbas/large-script.webp)
```

2023-01-05 14:56 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +For commonly-used SQL statements, you can save them as sheets and set up a public SQL script library in your team. For large SQL scripts (up to 100M), you can use them in issues after uploading them
```suggestion
For commonly-used SQL statements, you can save them as sheets and set up a public SQL script library in your team. For large SQL scripts (up to 100M), you can use them in issues after uploading them as sheets (see the screenshot below). You can explore the document [Manage SQL Scripts with Sheet](/docs/sql-editor/manage-sql-scripts) to get additional details.
```

2023-01-05 14:56 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +When developers query tables containing sensitive columns in SQL Editor, the result of these columns will display as "**\*\***". You can learn the configuration details from the document [Anonymize D
```suggestion
When developers query tables containing sensitive columns in SQL Editor, the result of these columns will display as "**\*\***". You can learn the configuration details from the document [Anonymize Data](/docs/administration/anonymize-data).
```

2023-01-05 14:56 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +When users want to allow developers to access some databases in the production environment, they can mark the production environment as a protected environment and configure an allowlist. You can get
```suggestion
When users want to allow developers to access some databases in the production environment, they can mark the production environment as a protected environment and configure an allowlist. You can get more details from the document [Database Access Control](/docs/administration/database-access-control).
```

2023-01-05 16:18 UTC, Candybase commented
> I can't view the images, don't know why ...

Fixed

2023-01-05 17:46 UTC, tianzhou approved these changes
LGTM

2023-01-05 17:46 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +With the new SQL Editor in Bytebase Console, you can run database admin commands in Admin mode, anonymize sensitive data when executing queries, configure a database allowlist to manage database acce
```suggestion
With the new SQL Editor in Bytebase Console, you can run database admin commands in Admin mode, anonymize sensitive data when fetching query results, configure a database allowlist to manage database access permission, and save commonly-used SQL scripts to collaborate with team members. Besides that, you can inspect all queries in SQL Editor via audit logs.
```

2023-01-05 17:46 UTC, tianzhou commented on content/blog/the-sql-editor-for-developers-and-dbas.md
> +If you have any comments or questions, don’t hesitate to let us know. You can join our discord at https://discord.gg/Fac9nmZ95j to learn more about Bytebase.
```suggestion
If you have any comments or questions, don’t hesitate to let us know. You can join our [discord](https://discord.gg/Fac9nmZ95j) to learn more about Bytebase.
```

2023-01-06 07:38 UTC, adela-bytebase approved these changes
LGTM

2023-01-06 07:48 UTC, merged