docs: add a blog post for MongoDB
bytebase/bytebase.com pull request #735
Opened 2023-01-11 07:07 UTC by Candybase

2023-01-11 14:42 UTC, tianzhou requested changes

2023-01-11 14:42 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +## Why Add MongoDB Support
```suggestion
## Why MongoDB
```

2023-01-11 14:42 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +description: Bytebase v1.11.0 brings support for MongoDB. This blog post walks you through managing MongoDB with Bytebase.
```suggestion
description: Bytebase 1.11.0 brings MongoDB support. This blog post walks you through managing MongoDB with Bytebase. 
```

2023-01-11 14:42 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +![db-rank-3](/static/blog/bytebase-support-for-mongodb-is-available/db-rank-3.webp)
```suggestion
As the [DB-Engines](https://db-engines.com/en/ranking) ranking shows, MongoDB is the only NoSQL database in the top 5.
![db-rank-3](/static/blog/bytebase-support-for-mongodb-is-available/db-rank-3.webp)
```

2023-01-11 14:42 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +What’s more, our customers say that they wanted to use Bytebase to manage MongoDB, just like they manage database changes to MySQL and PostgreSQL with Bytebase. As you know, Bytebase constantly liste
```suggestion
Some Bytebase customers also have MongoDB besides MySQL/PostgreSQL, and they ask us if Bytebase can support MongoDB so they can manage all transactional database changes via Bytebase. Before MongoDB, Bytebase only supports databases having SQL interface. But the customers' request is reasonable, so the Bytebase team accepts the challenge and today we are excited to announce the MongoDB support.
```

2023-01-11 14:42 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +With Bytebase v1.11.0, you can add an instance to connect to a MongoDB deployment, then you can:
```suggestion
With [Bytebase 1.11.0](https://www.bytebase.com/changelog/bytebase-1-11-0), you can add an instance to connect to a MongoDB deployment, then you can: 
```

2023-01-11 14:42 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +Bytebase supports MongoDB 4.0, 5.0, and 6.0. Please try it out and find that it's missing something or stumbled upon a bug,  do not hesitate to let us know. We invite you to join our [discord](https:
```suggestion
Bytebase supports MongoDB 4.0, 5.0, and 6.0. Please follow [installation guide](/docs/get-started/install/overview) to try it out. You can also join our [discord](https://discord.gg/Fac9nmZ95j)) to discuss all things Bytebase, share your feedback, and get help from the community.
```

2023-01-11 14:42 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +## Want to try it Out
```suggestion
## Try MongoDB Yourself
```

2023-01-11 14:42 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +## How does it work
```suggestion
## Manage MongoDB Changes
```

2023-01-11 16:17 UTC, Candybase commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +title: Bytebase Support for MongoDB is Available
> Introducing MongoDB Support in Bytebase

What is the main difference between them?

2023-01-11 16:38 UTC, Candybase commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +description: Bytebase v1.11.0 brings support for MongoDB. This blog post walks you through managing MongoDB with Bytebase.
I'd like to know why Bytebase v1.11.0 is incorrect. I think they are both correct.

2023-01-11 16:50 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +description: Bytebase v1.11.0 brings support for MongoDB. This blog post walks you through managing MongoDB with Bytebase.
They are both correct. Just for consistency, we don't add v in other places.

As to why we choose 1.11.0 over v1.11.0, because less is usually causing less consistency.

2023-01-11 16:54 UTC, tianzhou commented on content/blog/bytebase-support-for-mongodb-is-available.md
> +title: Bytebase Support for MongoDB is Available
imperative sentence is usually more terse and suitable for the title (because we have limited space) .

Also the current wording leads to bad layout

![CleanShot 2023-01-12 at 00 53 11](https://user-images.githubusercontent.com/230323/211867457-00468c07-979e-492f-a518-1eb0bb9312d5.png)

2023-01-12 03:04 UTC, adela-bytebase approved these changes
LGTM

2023-01-12 03:28 UTC, tianzhou approved these changes
LGTM

2023-01-12 03:28 UTC, tianzhou commented on content/blog/introducing-mongodb-support-in-bytebase.md
> +Bytebase supports MongoDB 4.0, 5.0, and 6.0. Please follow [installation guide](/docs/get-started/install/overview) to try it out. You can also join our [discord](https://discord.gg/Fac9nmZ95j)) to d
```suggestion
Bytebase supports MongoDB 4.0, 5.0, and 6.0. Please follow [installation guide](/docs/get-started/install/overview) to try it out. You can also join our [discord](https://discord.gg/Fac9nmZ95j) to discuss all things Bytebase, share your feedback, and get help from the community.
```

2023-01-12 10:47 UTC, merged