docs: add stop using navicat blog
bytebase/bytebase.com pull request #737
Opened 2023-01-11 07:39 UTC by milasuperstar

Signed-off-by: Mila Wu <wumila1996@gmail.com>

2023-01-11 15:01 UTC, tianzhou requested changes

2023-01-11 15:01 UTC, tianzhou commented on content/blog/stop-using-navicat.md
> +Navicat is for individuals, and Bytebase is for teams. Navicat is a pure client software with comprehensive capability and smooth experience if you need to operate a database for a personal project.
```suggestion
**Navicat is for individuals, and Bytebase is for teams**. Navicat is a pure client software with comprehensive capability and smooth experience if you need to operate a database for a personal project. However, when it comes to team use cases, where DBAs and developers need to collaborate, and DBAs need to control the database access, queries, changes, and other operations, products like Bytebase are desired to centralize the control and secure your orgnization’s most valuable asset, the database data.
```

2023-01-12 07:12 UTC, milasuperstar commented on content/blog/stop-using-navicat.md
> +As a client-side software, Navicat needs the username and password to access the database.  In a team environment, for developers to use their databases, DBAs must distribute the database credentials
ah😓 thats why it looked weird

2023-01-12 09:47 UTC, tianzhou approved these changes
LGTM

2023-01-12 09:47 UTC, merged