docs: Terraform announcement
bytebase/bytebase.com pull request #756
Opened 2023-01-23 08:54 UTC by Candybase

2023-01-24 07:20 UTC, tianzhou requested changes

2023-01-24 07:20 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +Terraform is an open-source tool that allows you to manage and provision infrastructure using code. It is known for its ability to work across multiple cloud providers, reusability, versioning, flexi
```suggestion
Terraform is the most widely used open-source tool that allows you to manage and provision infrastructure using code. It is known for its ability to work across multiple cloud providers, reusability, versioning, flexibility, and active community. [Terraform providers](https://developer.hashicorp.com/terraform/language/providers) are plugins that enable Terraform to communicate and manage resources on various cloud platforms such as AWS, Google Cloud, Azure, as well as SaaS vendors like DataDog, MongoDB, Elastic, and etc.
```

2023-01-24 07:20 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +Some Bytebase customers use Terraform to manage their infrastructure resources, and they want to use it to manage their Bytebase resources such as environments, database instances, and policies. Prev
```suggestion
Some Bytebase customers use Terraform to manage their infrastructure resources, and they want to use it to manage their Bytebase resources such as environments, database instances, and policies. Previously, we offered customers the web-based Bytebase Console and OpenAPI to do that. Today, we are excited to reveal our latest feature, [Terraform Bytebase Provider](https://registry.terraform.io/providers/bytebase/bytebase/latest/docs), which enables you to manage Bytebase resources through Terraform. This is a great opportunity for you to simplify and streamline your database management.
```

2023-01-24 07:20 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +Terraform is an open-source tool that allows you to manage and provision infrastructure using code. It is known for its ability to work across multiple cloud providers, reusability, versioning, flexi
No need to convince the popularity of Terraform to the audience since we are not introducing Terraform.

2023-01-24 07:20 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +Take the database access control policy as an example; we can grant developers access permission to the database “employee” in the environment “prod”. Currently, developers are not able to query data
If we do want to show the difference before and after the config, then we should have an after graph for the SQL Editor as well. 

While I feel we can get rid of this paragraph entirely.

2023-01-24 07:20 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +![access-control-code](/static/blog/introducing-terraform-bytebase-provider/access-control-code.webp)
```suggestion
The code block below demonstrates how to grant developers access permission to the database "employee" in the environment "prod":
- The first `access_control_all` policy resource defines that by default no database access is allowed in the `prod` environment.
- The second `access_control_database` policy resource defines that database `employee` under the `prod` environment is granted the database access specifically.
![access-control-code](/static/blog/introducing-terraform-bytebase-provider/access-control-code.webp)
```

2023-01-24 07:20 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +You are welcome to join [our discord](https://discord.gg/H7Ayn5NP) to learn more about database migration management and discuss related topics.
```suggestion
You are welcome to join [our discord](https://discord.gg/H7Ayn5NP) to learn more about database change management and discuss related topics.
```

2023-01-24 07:20 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +- Environments: They are modeled after different stages in the development pipeline, such as dev, test, and prod.
Bold these text. Same below

2023-01-24 16:11 UTC, Candybase commented on content/blog/introducing-terraform-bytebase-provider.md
> +- Environments: They are modeled after different stages in the development pipeline, such as dev, test, and prod.
done

2023-01-24 17:14 UTC, Candybase commented on content/blog/introducing-terraform-bytebase-provider.md
> +Take the database access control policy as an example; we can grant developers access permission to the database “employee” in the environment “prod”. Currently, developers are not able to query data
I will show the difference with the "access control" configuration. So, I replace the screenshot "SQL Editor" with the screenshot "access control"

2023-01-30 14:37 UTC, tianzhou requested changes

2023-01-30 14:37 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +published_at: 2023/01/20 13:37:17
```suggestion
published_at: 2023/02/08 13:37:17
```

2023-01-30 14:37 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +[Terraform](https://www.terraform.io/) is the most widely used open-source tool that allows you to manage and provision infrastructure using code. It is known for its ability to work across multiple
```suggestion
[Terraform](https://www.terraform.io/) is the most widely used open-source tool that allows you to manage and provision infrastructure using code. It is known for its ability to work across multiple cloud providers, reusability, versioning, flexibility, and active community. [Terraform providers](https://developer.hashicorp.com/terraform/language/providers) are plugins that enable Terraform to communicate and manage resources on various cloud platforms such as AWS, Google Cloud, Azure, as well as SaaS vendors like Datadog, MongoDB, Elastic, and etc.
```

2023-01-30 14:37 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +  - **Approval**: It determines whether database migration tasks in a particular environment are performed automatically or require manual approval before execution.
```suggestion
  - **Approval**: It determines whether database change tasks in a particular environment are performed automatically or require manual approval before execution.
```

2023-01-30 14:37 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +  - **Database backup schedul**e: It allows you to configure the database backup plan to be weekly, daily, or no backup plan, and also specify the backup data retention duration.
```suggestion
  - **Database backup schedule**: It allows you to configure the database backup plan to be weekly, daily, or none, and also specify the backup data retention period.
```

2023-01-30 14:37 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +  - **SQL review**: It enables you to customize SQL lint to check for common issues before execution. Currently, we have 48 SQL review rules for MySQL and 14 rules for PostgreSQL (more rules will com
```suggestion
  - **SQL Review**: It enables you to customize SQL lint to check for common issues before execution. Currently, we have 48 SQL Review rules for MySQL and 14 rules for PostgreSQL (more rules are coming).
```

2023-01-30 14:37 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +Taking the database access control policy as an example, the environment `prod` is marked as a protected environment, all databases in this environment are disallowed to developers via SQL Editor. we
```suggestion
Taking the database access control policy as an example, the environment `prod` is marked as a protected environment, and by default, all databases in this environment are inaccessible to developers via SQL Editor. You need to add specific databases to the allo list to grant their access permission to developers. Initially, the allowlist is empty like the one below.
```

2023-01-30 14:37 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +Terraform Bytebase Provider allows you to easily manage environments, database instances, instance roles, and policies in Bytebase. To get started, you can follow this tutorial [Manage databases in B
```suggestion
If you are already using Terraform to manage your infrastructure, the Terraform Bytebase Provider will allow you to codify the database configuration and consolidate your workflow. To get started, you can follow this tutorial [Manage databases in Bytebase with Terraform](https://www.bytebase.com/blog/manage-databases-in-bytebase-with-terraform) and try it out by yourself. Additionally, you can find [more examples on GitHub](https://github.com/bytebase/terraform-provider-bytebase/tree/main/examples).
```

2023-01-31 04:09 UTC, Candybase commented on content/blog/introducing-terraform-bytebase-provider.md
> +  - **Approval**: It determines whether database migration tasks in a particular environment are performed automatically or require manual approval before execution.
We need to replace “migration” with “change” in our products, including content and software builds, Right?

2023-02-06 06:25 UTC, adela-bytebase approved these changes
LGTM

2023-02-06 06:49 UTC, tianzhou approved these changes
LGTM

2023-02-06 06:49 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +  - **SQL Review**: It enables you to customize SQL lint to check for common issues before execution. Currently, we have 48 SQL Review rules for MySQL and 14 rules for PostgreSQL (more rules are comi
```suggestion
  - **SQL Review**: It enables you to customize SQL lint to check for common issues before execution. Currently, we have 49 SQL Review rules for MySQL and 37 rules for PostgreSQL (more rules are coming).
```

2023-02-06 06:49 UTC, tianzhou commented on content/blog/introducing-terraform-bytebase-provider.md
> +Some Bytebase customers use Terraform to manage their infrastructure resources, and they want to use it to manage their Bytebase resources such as environments, database instances, and policies. Prev
```suggestion
Some Bytebase customers use Terraform to manage their infrastructure resources, and they want to use it to manage their Bytebase resources such as environments, database instances, and policies. Previously, we offered customers the web-based Bytebase Console and OpenAPI to do that. Today, we are excited to reveal our latest feature, [Terraform Bytebase Provider](https://registry.terraform.io/providers/bytebase/bytebase/latest/docs), which enables you to manage Bytebase resources through Terraform. This is a great opportunity for you to simplify and streamline your database change management.
```

2023-02-08 10:15 UTC, merged