doc: OAuth 2.0 user doc
bytebase/bytebase.com pull request #761
Opened 2023-01-31 15:05 UTC by boojack

2023-02-01 04:42 UTC, tianzhou requested changes

2023-02-01 04:42 UTC, tianzhou commented on content/docs/_layout.md
> +### [Single sign-on (SSO)](/administration/sso/overview)
Single Sign-On

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/overview.md
> +Bytebase supports the following standard protocols that provide SSO.
```suggestion
Bytebase supports the following standard protocols that provide SSO:
```

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/overview.md
> +As a **Workspace Owner**, you can create a SSO provider with the following steps.
```suggestion
As a **Workspace Owner**, you can create a SSO provider with the following steps:
```

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/overview.md
> +Once a valid SSO has been created, the user can quickly log in via the button in sign in page.
```suggestion
Once a valid SSO has been created, the user can choose the configured SSO provider to sign in.
```

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +OAuth (Open Authorization) is an open standard for token-based authentication and authorization which is used to provide single sign-on (SSO). Bytebase supports to create popular OAuth 2.0 providers(
```suggestion
OAuth is an open standard for token-based authentication and authorization which is used to provide Single Sign-On (SSO). Bytebase supports popular OAuth 2.0 providers (GitHub, Google, GitLab) and custom providers.
```

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +In the creating SSO dialog, you need to fill in most of required fields. Including:
```suggestion
In the creating SSO dialog, you need to fill following fields:
```

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +  - **User information URL** is the API address for obtaining user information by accessToken;
These fields are not shown in the above screenshot

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +  - **ResourceID** should be an unique string about this resource;
```suggestion
  - **Resource ID** should be a unique string identifying this resource by Bytebase;
```

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +  - **Scopes** is the scope parameter carried when accessing the OAuth2 URL, which is filled in according to the requirements of the custom provider;
```suggestion
  - **Scopes** is the scope parameter carried when accessing the OAuth2 URL, which is filled in according to the custom provider;
```

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +  - **Token URL** is the API address for obtaining accessToken;
Should accessToken be access token?

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +- User information field mapping:
No screenshot

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +- Basic information:
I feel for the entire section should use a ## Overview

and each should use ### Basic information

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +## Create OAuth 2.0 provider with templates
Built-in OAuth Provider

![CleanShot 2023-02-01 at 12 33 27](https://user-images.githubusercontent.com/230323/215949520-edb97265-71a0-461d-9893-5ad85dda3512.png)

Long title should be avoided

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +   The Authorization callback URL is related with Bytebase's external URL.
Need to provide link to the external URL doc. https://bytebase-com-git-steven-byt-2356-oauth2-user-doc-bytebase.vercel.app/docs/get-started/install/external-url

Also, instead of using related, be more explicit about the rules.

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +2. Open creating SSO dialog and select the **GitLab** template.
If user just jumps to the GitLab section, they don't know what to fill for Redirect URI

2023-02-01 04:42 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +Bytebase provides some popular OAuth 2.0 provider templates including GitHub, GitLab and Google.
```suggestion
Bytebase provides templates for configuring built-in OAuth providers.
```

2023-02-01 09:03 UTC, boojack commented on content/docs/administration/sso/oauth2.md
> +2. Open creating SSO dialog and select the **GitLab** template.
<img width="869" alt="image" src="https://user-images.githubusercontent.com/24653555/215998155-6cec68a5-8cad-4bd8-84fd-7227856223ab.png">

Added a hint block in the beginning of section.

2023-02-01 09:04 UTC, boojack commented
PTAL

2023-02-01 09:36 UTC, tianzhou approved these changes
LGTM

2023-02-01 09:36 UTC, tianzhou commented on content/docs/_layout.md
> +### [Single sign-on](/administration/sso/overview)
```suggestion
### [Single Sign-On](/administration/sso/overview)
```

2023-02-01 09:36 UTC, tianzhou commented on content/docs/administration/sso/oauth2.md
> +OAuth is an open standard for token-based authentication and authorization which is used to provide single sign-on (SSO). Bytebase supports to create popular OAuth 2.0 providers(GitHub, Google, GitLa
```suggestion
OAuth is an open standard for token-based authentication and authorization which is used to provide Single Sign-On (SSO). Bytebase supports to create popular OAuth 2.0 providers (GitHub, Google, GitLab) and custom providers.
```

2023-02-01 09:36 UTC, tianzhou commented on content/docs/administration/sso/overview.md
> +title: Single sign-on (SSO)
```suggestion
title: Single Sign-On (SSO)
```

2023-02-01 09:36 UTC, tianzhou commented on content/docs/administration/sso/overview.md
> +Single sign-on (SSO) is an authentication method that enables users to securely authenticate with multiple applications and websites by using just one set of credentials.
```suggestion
Single Sign-On (SSO) is an authentication method that enables users to securely authenticate with multiple applications and websites by using just one set of credentials.
```

2023-02-02 02:05 UTC, d-bytebase approved these changes

2023-02-02 02:05 UTC, merged