docs: upload mysql x bytebase tutorial
bytebase/bytebase.com pull request #779
Opened 2023-02-03 09:42 UTC by milasuperstar

Signed-off-by: Mila Wu <wumila1996@gmail.com>

2023-02-04 03:32 UTC, tianzhou requested changes

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +description: MySQL is an open-source relational database management system developed by Oracle that is based on structured query language. This tutorial will guide you step-by-step to set up database
```suggestion
description: MySQL is the most popular open-source relational database management system. This tutorial will guide you step-by-step to set up database change management for MySQL in Bytebase.
```

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +[MySQL](https://www.mysql.com/) is an open-source relational database management system (RDBMS) developed by Oracle that is based on structured query language (SQL).
```suggestion
[MySQL](https://www.mysql.com/) is the most popular open-source relational database management system.
```

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +In the end is a bonus section about **Drift Detection** for those advanced users.
```suggestion
At the end, there is a bonus section about **Schema Drift Detection** for those advanced users.
```

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +1. After the instance is created, you can follow the onboarding guide if it’s your first time using Bytebase. If not, click on **New Project** to create a new project.
The New Project button is removed from the latest release. Need to visit the Project page.

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +![issue-create-db](/static/blog/database-change-management-with-mysql/issue-create-db)
image broken

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +2. Choose `demo` and click **Next**. This is where you get to try out the new **Schema Editor**. It’s a visual editor for schema changes. It’s still in beta, so please try it out and give us feedback
```suggestion
2. Choose `demo` and click **Next**. This is where you get to try out the new **Schema Editor**. It’s a visual editor for schema changes.
```

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +2. Choose `demo` and click **Next**. This is where you get to try out the new **Schema Editor**. It’s a visual editor for schema changes. It’s still in beta, so please try it out and give us feedback
Bear in mind it will exit beta at one point. So try to avoid time-sensitive information. So that we don't need to refined it later.

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +3. Click on **View diff**, you will see the exact drift. Use baseline to reconcile the schema state from the live database schema. Go to your database > **Migration History** > click **Establish new
`see the exact drift` step should be separated and provide the diff screenshot.

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +4. Bytebase will create an issue. Click **Resolve** to mark it done.
```suggestion
4. Bytebase will create a baseline issue. Click **Resolve** to mark it done.
```

2023-02-04 03:32 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +Now you have connected MySQL with Bytebase, and used the UI workflow to accomplish schema change. Bytebase will record the full migration history for you. With the **Enterprise Plan**, you can enjoy
```suggestion
Now you have connected MySQL with Bytebase, and used the UI workflow to accomplish schema change. Bytebase will record the full migration history for you. Furthermore, the **Enterprise Plan** is equipped with Schema Drift Detection to detect out-of-band schema changes performed outside of Bytebase.
```

2023-02-06 09:55 UTC, milasuperstar commented
Suggestions are applied, and did some changing to match the current version (12.0.0) as it was impossible to mention the missing **New Project** button otherwise 🤣 @tianzhou

2023-02-07 04:12 UTC, tianzhou approved these changes
LGTM

2023-02-07 04:12 UTC, tianzhou commented on content/blog/database-change-management-with-mysql.md
> +published_at: 2023/02/03 21:15
```suggestion
published_at: 2023/02/07 11:00
```

2023-02-07 04:16 UTC, merged