docs: rename protected env to production env
bytebase/bytebase.com pull request #799
Opened 2023-02-13 06:49 UTC by LiuJi-Jim

### Changes

- Rename "protected environment" to "production environment".
- Related screenshots updated.
- Some minor screenshots update
  - Sensitive data example with the new tooltip.
  - New schema panel in SQL Editor.

### Screenshots

![image](https://user-images.githubusercontent.com/2749742/218389912-e274bc99-9e63-4eb9-bea1-497aea81300e.png)

2023-02-13 06:57 UTC, tianzhou requested changes

2023-02-13 06:57 UTC, tianzhou commented on content/docs/administration/environment-policy/tier.md
>  ![tier-envs](/static/docs/administration/tier/env-tier-envs.webp)
Marks the wrong text

![CleanShot 2023-02-13 at 14 57 23](https://user-images.githubusercontent.com/230323/218391258-2a2c90fd-5c9a-41a3-94d7-57fca8f239c4.png)

2023-02-14 01:23 UTC, LiuJi-Jim commented
Screenshots updated. PTAL @tianzhou

2023-02-14 01:33 UTC, tianzhou approved these changes
LGTM

2023-02-14 01:33 UTC, merged