Update img link tenant database management
bytebase/bytebase.com pull request #82
Opened 2022-04-13 02:24 UTC by adela-bytebase

There are some link URLs look like https://lh5.googleusercontent.com/rMDiat5aaHH5Y4W11dyJJ6BaQFBKpgWpN1fe7I6KDa5Lr9KFl8IBvkDxBTN9PfWnUciyFsDPrp4MM2IMXKBbEunyWjfR4OoTA9LwcBci_DnTvrqAcEv17toC9P5V7sztyyhsHtOI , updated them into static/docs-assets/xxxx.png

2022-04-13 02:34 UTC, boojack commented
Maybe you need to upload those images in this PR.

2022-04-13 02:42 UTC, raytian03 commented on docs/features/tenant-database-mamangement.md
> +A label is a key-value pair that helps you identify the tenant for a database. The supported label keys are location and tenant currently. Workspace owner needs to predefine label values (tenant name
ddd should be removed.

2022-04-13 02:48 UTC, raytian03 requested changes
Please upload the images

2022-04-13 03:11 UTC, boojack requested changes
extra blank line should be removed.

2022-04-13 03:11 UTC, boojack commented on docs/features/tenant-database-mamangement.md
> +
```suggestion
```

2022-04-13 03:11 UTC, boojack commented on docs/features/tenant-database-mamangement.md
> +
```suggestion
```

2022-04-13 03:28 UTC, raytian03 submitted a review, later dismissed
LGTM

2022-04-13 03:28 UTC, boojack commented on docs/features/tenant-database-mamangement.md
> +![Create Database with Tenant Label](/static/docs-assets/create-database-with-tenant-label.png)
This image is not found.
```suggestion
![Create Database with Tenant Label](/static/docs-assets/tntdbmngmt-create-database-with-tenant-label.png)
```

2022-04-13 03:45 UTC, boojack approved these changes
LGTM

2022-04-18 02:41 UTC, tianzhou commented
@adela-bytebase There are conflicts you need to resolve.

2022-04-18 02:50 UTC, d-bytebase approved these changes

2022-04-19 06:14 UTC, merged